export declare type TScreenReaders = 'sr-only' | 'not-sr-only';
export declare type TAccessibility = TScreenReaders;
export declare type TBackgroundAttachment = 'bg-fixed' | 'bg-local' | 'bg-scroll';
export declare type TBackgroundClip = 'bg-clip-border' | 'bg-clip-padding' | 'bg-clip-content' | 'bg-clip-text';
export declare type TBackgroundOrigin = 'bg-origin-border' | 'bg-origin-padding' | 'bg-origin-content';
export declare type TBackgroundRepeat = 'bg-repeat' | 'bg-no-repeat' | 'bg-repeat-x' | 'bg-repeat-y' | 'bg-repeat-round' | 'bg-repeat-space';
export declare type TBackgroundOpacity = 'bg-opacity-0' | 'bg-opacity-5' | 'bg-opacity-10' | 'bg-opacity-20' | 'bg-opacity-25' | 'bg-opacity-30' | 'bg-opacity-40' | 'bg-opacity-50' | 'bg-opacity-60' | 'bg-opacity-70' | 'bg-opacity-75' | 'bg-opacity-80' | 'bg-opacity-90' | 'bg-opacity-95' | 'bg-opacity-100';
export declare type TBackgroundColor = 'bg-current' | 'bg-transparent' | 'bg-lighten-100' | 'bg-darken-100' | 'bg-code' | 'bg-primary' | 'bg-primary-tint' | 'bg-primary-light' | 'bg-primary-dark' | 'bg-primary-darker' | 'bg-secondary' | 'bg-secondary-tint' | 'bg-secondary-light' | 'bg-secondary-dark' | 'bg-secondary-darker' | 'bg-success' | 'bg-success-tint' | 'bg-success-light' | 'bg-success-dark' | 'bg-success-darker' | 'bg-warning' | 'bg-warning-tint' | 'bg-warning-light' | 'bg-warning-dark' | 'bg-warning-darker' | 'bg-danger' | 'bg-danger-tint' | 'bg-danger-light' | 'bg-danger-dark' | 'bg-danger-darker' | 'bg-on-code' | 'bg-on-primary' | 'bg-on-success' | 'bg-on-warning' | 'bg-on-danger' | 'bg-canvas-pure' | 'bg-canvas' | 'bg-canvas-tint' | 'bg-canvas-tint-more' | 'bg-canvas-50' | 'bg-canvas-100' | 'bg-canvas-200' | 'bg-canvas-300' | 'bg-canvas-400' | 'bg-canvas-500' | 'bg-canvas-600' | 'bg-canvas-700' | 'bg-canvas-800' | 'bg-canvas-900' | 'bg-canvas-1000' | 'bg-canvas-dialog' | 'bg-body' | 'bg-body-muted' | 'bg-body-light';
export declare type TBackgroundPosition = 'bg-bottom' | 'bg-center' | 'bg-left' | 'bg-left-bottom' | 'bg-left-top' | 'bg-right' | 'bg-right-bottom' | 'bg-right-top' | 'bg-top';
export declare type TBackgroundSize = 'bg-auto' | 'bg-cover' | 'bg-contain';
export declare type TBackgroundImage = 'bg-none';
export declare type TGradientColorStops = 'from-current' | 'via-current' | 'to-current' | 'from-transparent' | 'via-transparent' | 'to-transparent' | 'from-lighten-100' | 'via-lighten-100' | 'to-lighten-100' | 'from-darken-100' | 'via-darken-100' | 'to-darken-100' | 'from-code' | 'via-code' | 'to-code' | 'from-primary' | 'via-primary' | 'to-primary' | 'from-primary-tint' | 'via-primary-tint' | 'to-primary-tint' | 'from-primary-light' | 'via-primary-light' | 'to-primary-light' | 'from-primary-dark' | 'via-primary-dark' | 'to-primary-dark' | 'from-primary-darker' | 'via-primary-darker' | 'to-primary-darker' | 'from-secondary' | 'via-secondary' | 'to-secondary' | 'from-secondary-tint' | 'via-secondary-tint' | 'to-secondary-tint' | 'from-secondary-light' | 'via-secondary-light' | 'to-secondary-light' | 'from-secondary-dark' | 'via-secondary-dark' | 'to-secondary-dark' | 'from-secondary-darker' | 'via-secondary-darker' | 'to-secondary-darker' | 'from-success' | 'via-success' | 'to-success' | 'from-success-tint' | 'via-success-tint' | 'to-success-tint' | 'from-success-light' | 'via-success-light' | 'to-success-light' | 'from-success-dark' | 'via-success-dark' | 'to-success-dark' | 'from-success-darker' | 'via-success-darker' | 'to-success-darker' | 'from-warning' | 'via-warning' | 'to-warning' | 'from-warning-tint' | 'via-warning-tint' | 'to-warning-tint' | 'from-warning-light' | 'via-warning-light' | 'to-warning-light' | 'from-warning-dark' | 'via-warning-dark' | 'to-warning-dark' | 'from-warning-darker' | 'via-warning-darker' | 'to-warning-darker' | 'from-danger' | 'via-danger' | 'to-danger' | 'from-danger-tint' | 'via-danger-tint' | 'to-danger-tint' | 'from-danger-light' | 'via-danger-light' | 'to-danger-light' | 'from-danger-dark' | 'via-danger-dark' | 'to-danger-dark' | 'from-danger-darker' | 'via-danger-darker' | 'to-danger-darker' | 'from-on-code' | 'via-on-code' | 'to-on-code' | 'from-on-primary' | 'via-on-primary' | 'to-on-primary' | 'from-on-success' | 'via-on-success' | 'to-on-success' | 'from-on-warning' | 'via-on-warning' | 'to-on-warning' | 'from-on-danger' | 'via-on-danger' | 'to-on-danger';
export declare type TBackgrounds = TBackgroundAttachment | TBackgroundClip | TBackgroundOrigin | TBackgroundRepeat | TBackgroundOpacity | TBackgroundColor | TBackgroundPosition | TBackgroundSize | TBackgroundImage | TGradientColorStops;
export declare type TBorderStyle = 'border-solid' | 'border-dashed' | 'border-dotted' | 'border-double' | 'border-hidden' | 'border-none';
export declare type TDivideStyle = 'divide-solid' | 'divide-dashed' | 'divide-dotted' | 'divide-double' | 'divide-none';
export declare type TOutlineStyle = 'outline' | 'outline-dashed' | 'outline-dotted' | 'outline-double' | 'outline-hidden' | 'outline-none';
export declare type TBorderColor = 'border-current' | 'border-t-current' | 'border-r-current' | 'border-b-current' | 'border-l-current' | 'border-transparent' | 'border-t-transparent' | 'border-r-transparent' | 'border-b-transparent' | 'border-l-transparent' | 'border-lighten-100' | 'border-t-lighten-100' | 'border-r-lighten-100' | 'border-b-lighten-100' | 'border-l-lighten-100' | 'border-darken-100' | 'border-t-darken-100' | 'border-r-darken-100' | 'border-b-darken-100' | 'border-l-darken-100' | 'border-code' | 'border-t-code' | 'border-r-code' | 'border-b-code' | 'border-l-code' | 'border-primary' | 'border-t-primary' | 'border-r-primary' | 'border-b-primary' | 'border-l-primary' | 'border-primary-tint' | 'border-t-primary-tint' | 'border-r-primary-tint' | 'border-b-primary-tint' | 'border-l-primary-tint' | 'border-primary-light' | 'border-t-primary-light' | 'border-r-primary-light' | 'border-b-primary-light' | 'border-l-primary-light' | 'border-primary-dark' | 'border-t-primary-dark' | 'border-r-primary-dark' | 'border-b-primary-dark' | 'border-l-primary-dark' | 'border-primary-darker' | 'border-t-primary-darker' | 'border-r-primary-darker' | 'border-b-primary-darker' | 'border-l-primary-darker' | 'border-secondary' | 'border-t-secondary' | 'border-r-secondary' | 'border-b-secondary' | 'border-l-secondary' | 'border-secondary-tint' | 'border-t-secondary-tint' | 'border-r-secondary-tint' | 'border-b-secondary-tint' | 'border-l-secondary-tint' | 'border-secondary-light' | 'border-t-secondary-light' | 'border-r-secondary-light' | 'border-b-secondary-light' | 'border-l-secondary-light' | 'border-secondary-dark' | 'border-t-secondary-dark' | 'border-r-secondary-dark' | 'border-b-secondary-dark' | 'border-l-secondary-dark' | 'border-secondary-darker' | 'border-t-secondary-darker' | 'border-r-secondary-darker' | 'border-b-secondary-darker' | 'border-l-secondary-darker' | 'border-success' | 'border-t-success' | 'border-r-success' | 'border-b-success' | 'border-l-success' | 'border-success-tint' | 'border-t-success-tint' | 'border-r-success-tint' | 'border-b-success-tint' | 'border-l-success-tint' | 'border-success-light' | 'border-t-success-light' | 'border-r-success-light' | 'border-b-success-light' | 'border-l-success-light' | 'border-success-dark' | 'border-t-success-dark' | 'border-r-success-dark' | 'border-b-success-dark' | 'border-l-success-dark' | 'border-success-darker' | 'border-t-success-darker' | 'border-r-success-darker' | 'border-b-success-darker' | 'border-l-success-darker' | 'border-warning' | 'border-t-warning' | 'border-r-warning' | 'border-b-warning' | 'border-l-warning' | 'border-warning-tint' | 'border-t-warning-tint' | 'border-r-warning-tint' | 'border-b-warning-tint' | 'border-l-warning-tint' | 'border-warning-light' | 'border-t-warning-light' | 'border-r-warning-light' | 'border-b-warning-light' | 'border-l-warning-light' | 'border-warning-dark' | 'border-t-warning-dark' | 'border-r-warning-dark' | 'border-b-warning-dark' | 'border-l-warning-dark' | 'border-warning-darker' | 'border-t-warning-darker' | 'border-r-warning-darker' | 'border-b-warning-darker' | 'border-l-warning-darker' | 'border-danger' | 'border-t-danger' | 'border-r-danger' | 'border-b-danger' | 'border-l-danger' | 'border-danger-tint' | 'border-t-danger-tint' | 'border-r-danger-tint' | 'border-b-danger-tint' | 'border-l-danger-tint' | 'border-danger-light' | 'border-t-danger-light' | 'border-r-danger-light' | 'border-b-danger-light' | 'border-l-danger-light' | 'border-danger-dark' | 'border-t-danger-dark' | 'border-r-danger-dark' | 'border-b-danger-dark' | 'border-l-danger-dark' | 'border-danger-darker' | 'border-t-danger-darker' | 'border-r-danger-darker' | 'border-b-danger-darker' | 'border-l-danger-darker' | 'border-on-code' | 'border-t-on-code' | 'border-r-on-code' | 'border-b-on-code' | 'border-l-on-code' | 'border-on-primary' | 'border-t-on-primary' | 'border-r-on-primary' | 'border-b-on-primary' | 'border-l-on-primary' | 'border-on-success' | 'border-t-on-success' | 'border-r-on-success' | 'border-b-on-success' | 'border-l-on-success' | 'border-on-warning' | 'border-t-on-warning' | 'border-r-on-warning' | 'border-b-on-warning' | 'border-l-on-warning' | 'border-on-danger' | 'border-t-on-danger' | 'border-r-on-danger' | 'border-b-on-danger' | 'border-l-on-danger' | 'border-light' | 'border-t-light' | 'border-r-light' | 'border-b-light' | 'border-l-light' | 'border-dark' | 'border-t-dark' | 'border-r-dark' | 'border-b-dark' | 'border-l-dark' | 'border-button' | 'border-t-button' | 'border-r-button' | 'border-b-button' | 'border-l-button' | 'border-input' | 'border-t-input' | 'border-r-input' | 'border-b-input' | 'border-l-input' | 'border-body' | 'border-t-body' | 'border-r-body' | 'border-b-body' | 'border-l-body';
export declare type TBorderOpacity = 'border-opacity-0' | 'border-opacity-5' | 'border-opacity-10' | 'border-opacity-20' | 'border-opacity-25' | 'border-opacity-30' | 'border-opacity-40' | 'border-opacity-50' | 'border-opacity-60' | 'border-opacity-70' | 'border-opacity-75' | 'border-opacity-80' | 'border-opacity-90' | 'border-opacity-95' | 'border-opacity-100';
export declare type TBorderRadius = 'rounded-t-none' | 'rounded-r-none' | 'rounded-b-none' | 'rounded-l-none' | 'rounded-tr-none' | 'rounded-tl-none' | 'rounded-br-none' | 'rounded-bl-none' | 'rounded-none' | 'rounded-t-sm' | 'rounded-r-sm' | 'rounded-b-sm' | 'rounded-l-sm' | 'rounded-tr-sm' | 'rounded-tl-sm' | 'rounded-br-sm' | 'rounded-bl-sm' | 'rounded-sm' | 'rounded-t' | 'rounded-r' | 'rounded-b' | 'rounded-l' | 'rounded-tr' | 'rounded-tl' | 'rounded-br' | 'rounded-bl' | 'rounded' | 'rounded-t-lg' | 'rounded-r-lg' | 'rounded-b-lg' | 'rounded-l-lg' | 'rounded-tr-lg' | 'rounded-tl-lg' | 'rounded-br-lg' | 'rounded-bl-lg' | 'rounded-lg' | 'rounded-t-xl' | 'rounded-r-xl' | 'rounded-b-xl' | 'rounded-l-xl' | 'rounded-tr-xl' | 'rounded-tl-xl' | 'rounded-br-xl' | 'rounded-bl-xl' | 'rounded-xl' | 'rounded-t-full' | 'rounded-r-full' | 'rounded-b-full' | 'rounded-l-full' | 'rounded-tr-full' | 'rounded-tl-full' | 'rounded-br-full' | 'rounded-bl-full' | 'rounded-full';
export declare type TBorderWidth = 'border-t-0' | 'border-r-0' | 'border-b-0' | 'border-l-0' | 'border-x-0' | 'border-y-0' | 'border-0' | 'border-t-1' | 'border-r-1' | 'border-b-1' | 'border-l-1' | 'border-x-1' | 'border-y-1' | 'border-1' | 'border-t-2' | 'border-r-2' | 'border-b-2' | 'border-l-2' | 'border-x-2' | 'border-y-2' | 'border-2' | 'border-t-4' | 'border-r-4' | 'border-b-4' | 'border-l-4' | 'border-x-4' | 'border-y-4' | 'border-4' | 'border-t-8' | 'border-r-8' | 'border-b-8' | 'border-l-8' | 'border-x-8' | 'border-y-8' | 'border-8' | 'border-t' | 'border-r' | 'border-b' | 'border-l' | 'border-x' | 'border-y' | 'border';
export declare type TDivideColor = 'divide-current' | 'divide-transparent' | 'divide-lighten-100' | 'divide-darken-100' | 'divide-code' | 'divide-primary' | 'divide-primary-tint' | 'divide-primary-light' | 'divide-primary-dark' | 'divide-primary-darker' | 'divide-secondary' | 'divide-secondary-tint' | 'divide-secondary-light' | 'divide-secondary-dark' | 'divide-secondary-darker' | 'divide-success' | 'divide-success-tint' | 'divide-success-light' | 'divide-success-dark' | 'divide-success-darker' | 'divide-warning' | 'divide-warning-tint' | 'divide-warning-light' | 'divide-warning-dark' | 'divide-warning-darker' | 'divide-danger' | 'divide-danger-tint' | 'divide-danger-light' | 'divide-danger-dark' | 'divide-danger-darker' | 'divide-on-code' | 'divide-on-primary' | 'divide-on-success' | 'divide-on-warning' | 'divide-on-danger' | 'divide-light' | 'divide-dark' | 'divide-button' | 'divide-input' | 'divide-body';
export declare type TDivideOpacity = 'divide-opacity-0' | 'divide-opacity-5' | 'divide-opacity-10' | 'divide-opacity-20' | 'divide-opacity-25' | 'divide-opacity-30' | 'divide-opacity-40' | 'divide-opacity-50' | 'divide-opacity-60' | 'divide-opacity-70' | 'divide-opacity-75' | 'divide-opacity-80' | 'divide-opacity-90' | 'divide-opacity-95' | 'divide-opacity-100';
export declare type TDivideWidth = 'divide-x-0' | 'divide-y-0' | 'divide-x-1' | 'divide-y-1' | 'divide-x-2' | 'divide-y-2' | 'divide-x-4' | 'divide-y-4' | 'divide-x-8' | 'divide-y-8' | 'divide-x' | 'divide-y' | 'divide-x-reverse' | 'divide-y-reverse';
export declare type TRingColor = 'ring-current' | 'ring-transparent' | 'ring-lighten-100' | 'ring-darken-100' | 'ring-code' | 'ring-primary' | 'ring-primary-tint' | 'ring-primary-light' | 'ring-primary-dark' | 'ring-primary-darker' | 'ring-secondary' | 'ring-secondary-tint' | 'ring-secondary-light' | 'ring-secondary-dark' | 'ring-secondary-darker' | 'ring-success' | 'ring-success-tint' | 'ring-success-light' | 'ring-success-dark' | 'ring-success-darker' | 'ring-warning' | 'ring-warning-tint' | 'ring-warning-light' | 'ring-warning-dark' | 'ring-warning-darker' | 'ring-danger' | 'ring-danger-tint' | 'ring-danger-light' | 'ring-danger-dark' | 'ring-danger-darker' | 'ring-on-code' | 'ring-on-primary' | 'ring-on-success' | 'ring-on-warning' | 'ring-on-danger';
export declare type TRingWidth = 'ring-0' | 'ring-1' | 'ring-2' | 'ring-4' | 'ring-8' | 'ring' | 'inset';
export declare type TRingOpacity = 'ring-opacity-0' | 'ring-opacity-5' | 'ring-opacity-10' | 'ring-opacity-20' | 'ring-opacity-25' | 'ring-opacity-30' | 'ring-opacity-40' | 'ring-opacity-50' | 'ring-opacity-60' | 'ring-opacity-70' | 'ring-opacity-75' | 'ring-opacity-80' | 'ring-opacity-90' | 'ring-opacity-95' | 'ring-opacity-100' | 'ring-opacity';
export declare type TRingOffsetColor = 'ring-offset-current' | 'ring-offset-transparent' | 'ring-offset-lighten-100' | 'ring-offset-darken-100' | 'ring-offset-code' | 'ring-offset-primary' | 'ring-offset-primary-tint' | 'ring-offset-primary-light' | 'ring-offset-primary-dark' | 'ring-offset-primary-darker' | 'ring-offset-secondary' | 'ring-offset-secondary-tint' | 'ring-offset-secondary-light' | 'ring-offset-secondary-dark' | 'ring-offset-secondary-darker' | 'ring-offset-success' | 'ring-offset-success-tint' | 'ring-offset-success-light' | 'ring-offset-success-dark' | 'ring-offset-success-darker' | 'ring-offset-warning' | 'ring-offset-warning-tint' | 'ring-offset-warning-light' | 'ring-offset-warning-dark' | 'ring-offset-warning-darker' | 'ring-offset-danger' | 'ring-offset-danger-tint' | 'ring-offset-danger-light' | 'ring-offset-danger-dark' | 'ring-offset-danger-darker' | 'ring-offset-on-code' | 'ring-offset-on-primary' | 'ring-offset-on-success' | 'ring-offset-on-warning' | 'ring-offset-on-danger';
export declare type TRingOffsetWidth = 'ring-offset-0' | 'ring-offset-1' | 'ring-offset-2' | 'ring-offset-4' | 'ring-offset-8';
export declare type TOutlineOffset = 'outline-0' | 'outline-1' | 'outline-2' | 'outline-4' | 'outline-8';
export declare type TOutlineWidth = 'outline-0' | 'outline-1' | 'outline-2' | 'outline-4' | 'outline-8';
export declare type TOutlineColor = 'outline-current' | 'outline-transparent' | 'outline-lighten-100' | 'outline-darken-100' | 'outline-code' | 'outline-primary' | 'outline-primary-tint' | 'outline-primary-light' | 'outline-primary-dark' | 'outline-primary-darker' | 'outline-secondary' | 'outline-secondary-tint' | 'outline-secondary-light' | 'outline-secondary-dark' | 'outline-secondary-darker' | 'outline-success' | 'outline-success-tint' | 'outline-success-light' | 'outline-success-dark' | 'outline-success-darker' | 'outline-warning' | 'outline-warning-tint' | 'outline-warning-light' | 'outline-warning-dark' | 'outline-warning-darker' | 'outline-danger' | 'outline-danger-tint' | 'outline-danger-light' | 'outline-danger-dark' | 'outline-danger-darker' | 'outline-on-code' | 'outline-on-primary' | 'outline-on-success' | 'outline-on-warning' | 'outline-on-danger';
export declare type TBorders = TBorderStyle | TDivideStyle | TOutlineStyle | TBorderColor | TBorderOpacity | TBorderRadius | TBorderWidth | TDivideColor | TDivideOpacity | TDivideWidth | TRingColor | TRingWidth | TRingOpacity | TRingOffsetColor | TRingOffsetWidth | TOutlineOffset | TOutlineWidth | TOutlineColor;
export declare type TBorderCollapse = 'border-collapse' | 'border-separate';
export declare type TTableLayout = 'table-auto' | 'table-fixed';
export declare type TTables = TBorderCollapse | TTableLayout;
export declare type TMixBlendMode = 'mix-blend-normal' | 'mix-blend-multiply' | 'mix-blend-screen' | 'mix-blend-overlay' | 'mix-blend-darken' | 'mix-blend-lighten' | 'mix-blend-color-dodge' | 'mix-blend-color-burn' | 'mix-blend-hard-light' | 'mix-blend-soft-light' | 'mix-blend-difference' | 'mix-blend-exclusion' | 'mix-blend-hue' | 'mix-blend-saturation' | 'mix-blend-color' | 'mix-blend-luminosity';
export declare type TBackgroundBlendMode = 'bg-blend-normal' | 'bg-blend-multiply' | 'bg-blend-screen' | 'bg-blend-overlay' | 'bg-blend-darken' | 'bg-blend-lighten' | 'bg-blend-color-dodge' | 'bg-blend-color-burn' | 'bg-blend-hard-light' | 'bg-blend-soft-light' | 'bg-blend-difference' | 'bg-blend-exclusion' | 'bg-blend-hue' | 'bg-blend-saturation' | 'bg-blend-color' | 'bg-blend-luminosity';
export declare type TBoxShadow = 'shadow-sm' | 'shadow' | 'shadow-md' | 'shadow-lg' | 'shadow-xl' | 'shadow-2xl';
export declare type TBoxShadowColor = 'shadow-current' | 'shadow-transparent' | 'shadow-lighten-100' | 'shadow-darken-100' | 'shadow-code' | 'shadow-primary' | 'shadow-primary-tint' | 'shadow-primary-light' | 'shadow-primary-dark' | 'shadow-primary-darker' | 'shadow-secondary' | 'shadow-secondary-tint' | 'shadow-secondary-light' | 'shadow-secondary-dark' | 'shadow-secondary-darker' | 'shadow-success' | 'shadow-success-tint' | 'shadow-success-light' | 'shadow-success-dark' | 'shadow-success-darker' | 'shadow-warning' | 'shadow-warning-tint' | 'shadow-warning-light' | 'shadow-warning-dark' | 'shadow-warning-darker' | 'shadow-danger' | 'shadow-danger-tint' | 'shadow-danger-light' | 'shadow-danger-dark' | 'shadow-danger-darker' | 'shadow-on-code' | 'shadow-on-primary' | 'shadow-on-success' | 'shadow-on-warning' | 'shadow-on-danger';
export declare type TOpacity = 'opacity-0' | 'opacity-5' | 'opacity-10' | 'opacity-20' | 'opacity-25' | 'opacity-30' | 'opacity-40' | 'opacity-50' | 'opacity-60' | 'opacity-70' | 'opacity-75' | 'opacity-80' | 'opacity-90' | 'opacity-95' | 'opacity-100';
export declare type TEffects = TMixBlendMode | TBackgroundBlendMode | TBoxShadow | TBoxShadowColor | TOpacity;
export declare type TTransitionProperty = 'transition-none' | 'transition-all' | 'transition' | 'transition-colors' | 'transition-opacity' | 'transition-shadow' | 'transition-transform';
export declare type TTransitionDuration = 'duration-75' | 'duration-100' | 'duration-150' | 'duration-200' | 'duration-300' | 'duration-500' | 'duration-700' | 'duration-1000' | 'duration';
export declare type TTransitionTimingFunction = 'ease-linear' | 'ease-in' | 'ease-out' | 'ease-in-out';
export declare type TTransitionDelay = 'delay-75' | 'delay-100' | 'delay-150' | 'delay-200' | 'delay-300' | 'delay-500' | 'delay-700' | 'delay-1000';
export declare type TAnimation = 'animate-none' | 'animate-spin' | 'animate-ping' | 'animate-pulse' | 'animate-bounce';
export declare type TTransitionsAndAnimations = TTransitionProperty | TTransitionDuration | TTransitionTimingFunction | TTransitionDelay | TAnimation;
export declare type TFilter = 'filter' | 'filter-none';
export declare type TBackdropFilter = 'backdrop-filter' | 'backdrop-filter-none';
export declare type TBlur = 'blur-0' | 'blur-sm' | 'blur' | 'blur-md' | 'blur-lg' | 'blur-xl' | 'blur-2xl' | 'blur-3xl';
export declare type TBrightness = 'brightness-0' | 'brightness-50' | 'brightness-75' | 'brightness-90' | 'brightness-95' | 'brightness-100' | 'brightness-105' | 'brightness-110' | 'brightness-125' | 'brightness-150' | 'brightness-200';
export declare type TContrast = 'contrast-0' | 'contrast-50' | 'contrast-75' | 'contrast-100' | 'contrast-125' | 'contrast-150' | 'contrast-200';
export declare type TDropShadow = 'drop-shadow';
export declare type TGrayscale = 'grayscale-0' | 'grayscale';
export declare type THueRotate = 'hue-rotate-0' | 'hue-rotate-15' | 'hue-rotate-30' | 'hue-rotate-60' | 'hue-rotate-90' | 'hue-rotate-180';
export declare type TInvert = 'invert-0' | 'invert';
export declare type TSaturate = 'saturate-0' | 'saturate-50' | 'saturate-100' | 'saturate-150' | 'saturate-200';
export declare type TSepia = 'sepia-0' | 'sepia';
export declare type TBackdropBlur = 'backdrop-blur-0' | 'backdrop-blur-sm' | 'backdrop-blur' | 'backdrop-blur-md' | 'backdrop-blur-lg' | 'backdrop-blur-xl' | 'backdrop-blur-2xl' | 'backdrop-blur-3xl';
export declare type TBackdropBrightness = 'backdrop-brightness-0' | 'backdrop-brightness-50' | 'backdrop-brightness-75' | 'backdrop-brightness-90' | 'backdrop-brightness-95' | 'backdrop-brightness-100' | 'backdrop-brightness-105' | 'backdrop-brightness-110' | 'backdrop-brightness-125' | 'backdrop-brightness-150' | 'backdrop-brightness-200';
export declare type TBackdropContrast = 'backdrop-contrast-0' | 'backdrop-contrast-50' | 'backdrop-contrast-75' | 'backdrop-contrast-100' | 'backdrop-contrast-125' | 'backdrop-contrast-150' | 'backdrop-contrast-200';
export declare type TBackdropGrayscale = 'backdrop-grayscale-0' | 'backdrop-grayscale';
export declare type TBackdropHueRotate = 'backdrop-hue-rotate-0' | 'backdrop-hue-rotate-15' | 'backdrop-hue-rotate-30' | 'backdrop-hue-rotate-60' | 'backdrop-hue-rotate-90' | 'backdrop-hue-rotate-180';
export declare type TBackdropInvert = 'backdrop-invert-0' | 'backdrop-invert';
export declare type TBackdropOpacity = 'backdrop-opacity-0' | 'backdrop-opacity-5' | 'backdrop-opacity-10' | 'backdrop-opacity-20' | 'backdrop-opacity-25' | 'backdrop-opacity-30' | 'backdrop-opacity-40' | 'backdrop-opacity-50' | 'backdrop-opacity-60' | 'backdrop-opacity-70' | 'backdrop-opacity-75' | 'backdrop-opacity-80' | 'backdrop-opacity-90' | 'backdrop-opacity-95' | 'backdrop-opacity-100';
export declare type TBackdropSaturate = 'backdrop-saturate-0' | 'backdrop-saturate-50' | 'backdrop-saturate-100' | 'backdrop-saturate-150' | 'backdrop-saturate-200';
export declare type TBackdropSepia = 'backdrop-sepia-0' | 'backdrop-sepia';
export declare type TFilters = TFilter | TBackdropFilter | TBlur | TBrightness | TContrast | TDropShadow | TGrayscale | THueRotate | TInvert | TSaturate | TSepia | TBackdropBlur | TBackdropBrightness | TBackdropContrast | TBackdropGrayscale | TBackdropHueRotate | TBackdropInvert | TBackdropOpacity | TBackdropSaturate | TBackdropSepia;
export declare type TFlexDirection = 'flex-row' | 'flex-row-reverse' | 'flex-col' | 'flex-col-reverse';
export declare type TFlexWrap = 'flex-nowrap' | 'flex-wrap' | 'flex-wrap-reverse';
export declare type TAlignItems = 'items-stretch' | 'items-start' | 'items-center' | 'items-end' | 'items-baseline';
export declare type TAlignContent = 'content-start' | 'content-center' | 'content-end' | 'content-between' | 'content-around';
export declare type TAlignSelf = 'self-auto' | 'self-start' | 'self-center' | 'self-end' | 'self-stretch' | 'self-baseline';
export declare type TPlaceContent = 'place-content-start' | 'place-content-center' | 'place-content-end' | 'place-content-between' | 'place-content-around' | 'place-content-evenly' | 'place-content-stretch';
export declare type TPlaceItems = 'place-items-auto' | 'place-items-start' | 'place-items-center' | 'place-items-end' | 'place-items-stretch';
export declare type TPlaceSelf = 'place-self-auto' | 'place-self-start' | 'place-self-center' | 'place-self-end' | 'place-self-stretch';
export declare type TJustifyContent = 'justify-start' | 'justify-center' | 'justify-end' | 'justify-between' | 'justify-around' | 'justify-evenly';
export declare type TJustifyItems = 'justify-items-auto' | 'justify-items-start' | 'justify-items-center' | 'justify-items-end' | 'justify-items-stretch';
export declare type TJustifySelf = 'justify-self-auto' | 'justify-self-start' | 'justify-self-center' | 'justify-self-end' | 'justify-self-stretch';
export declare type TFlex = 'flex-initial' | 'flex-1' | 'flex-auto' | 'flex-none';
export declare type TFlexBasis = 'basis-0' | 'basis-1' | 'basis-2' | 'basis-3' | 'basis-4' | 'basis-5' | 'basis-6' | 'basis-7' | 'basis-8' | 'basis-9' | 'basis-10' | 'basis-11' | 'basis-12' | 'basis-14' | 'basis-16' | 'basis-20' | 'basis-24' | 'basis-28' | 'basis-32' | 'basis-36' | 'basis-40' | 'basis-44' | 'basis-48' | 'basis-52' | 'basis-56' | 'basis-60' | 'basis-64' | 'basis-72' | 'basis-80' | 'basis-96' | 'basis-px' | 'basis-0.5' | 'basis-1.5' | 'basis-2.5' | 'basis-3.5' | 'basis-1/2' | 'basis-1/3' | 'basis-2/3' | 'basis-1/4' | 'basis-2/4' | 'basis-3/4' | 'basis-1/5' | 'basis-2/5' | 'basis-3/5' | 'basis-4/5' | 'basis-1/6' | 'basis-2/6' | 'basis-3/6' | 'basis-4/6' | 'basis-5/6' | 'basis-1/12' | 'basis-2/12' | 'basis-3/12' | 'basis-4/12' | 'basis-5/12' | 'basis-6/12' | 'basis-7/12' | 'basis-8/12' | 'basis-9/12' | 'basis-10/12' | 'basis-11/12' | 'basis-auto' | 'basis-full';
export declare type TFlexGrow = 'grow-0' | 'grow';
export declare type TFlexShrink = 'shrink-0' | 'shrink';
export declare type TOrder = 'order-first' | 'order-last' | 'order-none';
export declare type TFlexBox = TFlexDirection | TFlexWrap | TAlignItems | TAlignContent | TAlignSelf | TPlaceContent | TPlaceItems | TPlaceSelf | TJustifyContent | TJustifyItems | TJustifySelf | TFlex | TFlexBasis | TFlexGrow | TFlexShrink | TOrder;
export declare type TGridAutoFlow = 'grid-flow-row' | 'grid-flow-col' | 'grid-flow-row-dense' | 'grid-flow-col-dense';
export declare type TGridTemplateColumns = 'grid-cols-none';
export declare type TGridAutoColumns = 'auto-cols-auto' | 'auto-cols-min' | 'auto-cols-max' | 'auto-cols-fr';
export declare type TGridColumn = 'col-auto' | 'col-span-full';
export declare type TGridColumnStart = 'col-start-1' | 'col-start-2' | 'col-start-3' | 'col-start-4' | 'col-start-5' | 'col-start-6' | 'col-start-7' | 'col-start-8' | 'col-start-9' | 'col-start-10' | 'col-start-11' | 'col-start-12' | 'col-start-13' | 'col-start-auto';
export declare type TGridColumnEnd = 'col-end-1' | 'col-end-2' | 'col-end-3' | 'col-end-4' | 'col-end-5' | 'col-end-6' | 'col-end-7' | 'col-end-8' | 'col-end-9' | 'col-end-10' | 'col-end-11' | 'col-end-12' | 'col-end-13' | 'col-end-auto';
export declare type TGridTemplateRows = 'grid-rows-none';
export declare type TGridAutoRows = 'auto-rows-auto' | 'auto-rows-min' | 'auto-rows-max' | 'auto-rows-fr';
export declare type TGridRow = 'row-auto' | 'row-span-full';
export declare type TGridRowStart = 'row-start-1' | 'row-start-2' | 'row-start-3' | 'row-start-4' | 'row-start-5' | 'row-start-6' | 'row-start-7' | 'row-start-auto';
export declare type TGridRowEnd = 'row-end-1' | 'row-end-2' | 'row-end-3' | 'row-end-4' | 'row-end-5' | 'row-end-6' | 'row-end-7' | 'row-end-auto';
export declare type TGap = 'gap-0' | 'gap-1' | 'gap-2' | 'gap-3' | 'gap-4' | 'gap-5' | 'gap-6' | 'gap-7' | 'gap-8' | 'gap-9' | 'gap-10' | 'gap-11' | 'gap-12' | 'gap-14' | 'gap-16' | 'gap-20' | 'gap-24' | 'gap-28' | 'gap-32' | 'gap-36' | 'gap-40' | 'gap-44' | 'gap-48' | 'gap-52' | 'gap-56' | 'gap-60' | 'gap-64' | 'gap-72' | 'gap-80' | 'gap-96' | 'gap-px' | 'gap-0.5' | 'gap-1.5' | 'gap-2.5' | 'gap-3.5' | 'gap-y-0' | 'gap-y-1' | 'gap-y-2' | 'gap-y-3' | 'gap-y-4' | 'gap-y-5' | 'gap-y-6' | 'gap-y-7' | 'gap-y-8' | 'gap-y-9' | 'gap-y-10' | 'gap-y-11' | 'gap-y-12' | 'gap-y-14' | 'gap-y-16' | 'gap-y-20' | 'gap-y-24' | 'gap-y-28' | 'gap-y-32' | 'gap-y-36' | 'gap-y-40' | 'gap-y-44' | 'gap-y-48' | 'gap-y-52' | 'gap-y-56' | 'gap-y-60' | 'gap-y-64' | 'gap-y-72' | 'gap-y-80' | 'gap-y-96' | 'gap-y-px' | 'gap-y-0.5' | 'gap-y-1.5' | 'gap-y-2.5' | 'gap-y-3.5' | 'gap-x-0' | 'gap-x-1' | 'gap-x-2' | 'gap-x-3' | 'gap-x-4' | 'gap-x-5' | 'gap-x-6' | 'gap-x-7' | 'gap-x-8' | 'gap-x-9' | 'gap-x-10' | 'gap-x-11' | 'gap-x-12' | 'gap-x-14' | 'gap-x-16' | 'gap-x-20' | 'gap-x-24' | 'gap-x-28' | 'gap-x-32' | 'gap-x-36' | 'gap-x-40' | 'gap-x-44' | 'gap-x-48' | 'gap-x-52' | 'gap-x-56' | 'gap-x-60' | 'gap-x-64' | 'gap-x-72' | 'gap-x-80' | 'gap-x-96' | 'gap-x-px' | 'gap-x-0.5' | 'gap-x-1.5' | 'gap-x-2.5' | 'gap-x-3.5';
export declare type TGrid = TGridAutoFlow | TGridTemplateColumns | TGridAutoColumns | TGridColumn | TGridColumnStart | TGridColumnEnd | TGridTemplateRows | TGridAutoRows | TGridRow | TGridRowStart | TGridRowEnd | TGap;
export declare type TPadding = 'p-0' | 'p-1' | 'p-2' | 'p-3' | 'p-4' | 'p-5' | 'p-6' | 'p-7' | 'p-8' | 'p-9' | 'p-10' | 'p-11' | 'p-12' | 'p-14' | 'p-16' | 'p-20' | 'p-24' | 'p-28' | 'p-32' | 'p-36' | 'p-40' | 'p-44' | 'p-48' | 'p-52' | 'p-56' | 'p-60' | 'p-64' | 'p-72' | 'p-80' | 'p-96' | 'p-px' | 'p-0.5' | 'p-1.5' | 'p-2.5' | 'p-3.5' | 'py-0' | 'py-1' | 'py-2' | 'py-3' | 'py-4' | 'py-5' | 'py-6' | 'py-7' | 'py-8' | 'py-9' | 'py-10' | 'py-11' | 'py-12' | 'py-14' | 'py-16' | 'py-20' | 'py-24' | 'py-28' | 'py-32' | 'py-36' | 'py-40' | 'py-44' | 'py-48' | 'py-52' | 'py-56' | 'py-60' | 'py-64' | 'py-72' | 'py-80' | 'py-96' | 'py-px' | 'py-0.5' | 'py-1.5' | 'py-2.5' | 'py-3.5' | 'px-0' | 'px-1' | 'px-2' | 'px-3' | 'px-4' | 'px-5' | 'px-6' | 'px-7' | 'px-8' | 'px-9' | 'px-10' | 'px-11' | 'px-12' | 'px-14' | 'px-16' | 'px-20' | 'px-24' | 'px-28' | 'px-32' | 'px-36' | 'px-40' | 'px-44' | 'px-48' | 'px-52' | 'px-56' | 'px-60' | 'px-64' | 'px-72' | 'px-80' | 'px-96' | 'px-px' | 'px-0.5' | 'px-1.5' | 'px-2.5' | 'px-3.5' | 'pt-0' | 'pt-1' | 'pt-2' | 'pt-3' | 'pt-4' | 'pt-5' | 'pt-6' | 'pt-7' | 'pt-8' | 'pt-9' | 'pt-10' | 'pt-11' | 'pt-12' | 'pt-14' | 'pt-16' | 'pt-20' | 'pt-24' | 'pt-28' | 'pt-32' | 'pt-36' | 'pt-40' | 'pt-44' | 'pt-48' | 'pt-52' | 'pt-56' | 'pt-60' | 'pt-64' | 'pt-72' | 'pt-80' | 'pt-96' | 'pt-px' | 'pt-0.5' | 'pt-1.5' | 'pt-2.5' | 'pt-3.5' | 'pr-0' | 'pr-1' | 'pr-2' | 'pr-3' | 'pr-4' | 'pr-5' | 'pr-6' | 'pr-7' | 'pr-8' | 'pr-9' | 'pr-10' | 'pr-11' | 'pr-12' | 'pr-14' | 'pr-16' | 'pr-20' | 'pr-24' | 'pr-28' | 'pr-32' | 'pr-36' | 'pr-40' | 'pr-44' | 'pr-48' | 'pr-52' | 'pr-56' | 'pr-60' | 'pr-64' | 'pr-72' | 'pr-80' | 'pr-96' | 'pr-px' | 'pr-0.5' | 'pr-1.5' | 'pr-2.5' | 'pr-3.5' | 'pb-0' | 'pb-1' | 'pb-2' | 'pb-3' | 'pb-4' | 'pb-5' | 'pb-6' | 'pb-7' | 'pb-8' | 'pb-9' | 'pb-10' | 'pb-11' | 'pb-12' | 'pb-14' | 'pb-16' | 'pb-20' | 'pb-24' | 'pb-28' | 'pb-32' | 'pb-36' | 'pb-40' | 'pb-44' | 'pb-48' | 'pb-52' | 'pb-56' | 'pb-60' | 'pb-64' | 'pb-72' | 'pb-80' | 'pb-96' | 'pb-px' | 'pb-0.5' | 'pb-1.5' | 'pb-2.5' | 'pb-3.5' | 'pl-0' | 'pl-1' | 'pl-2' | 'pl-3' | 'pl-4' | 'pl-5' | 'pl-6' | 'pl-7' | 'pl-8' | 'pl-9' | 'pl-10' | 'pl-11' | 'pl-12' | 'pl-14' | 'pl-16' | 'pl-20' | 'pl-24' | 'pl-28' | 'pl-32' | 'pl-36' | 'pl-40' | 'pl-44' | 'pl-48' | 'pl-52' | 'pl-56' | 'pl-60' | 'pl-64' | 'pl-72' | 'pl-80' | 'pl-96' | 'pl-px' | 'pl-0.5' | 'pl-1.5' | 'pl-2.5' | 'pl-3.5';
export declare type TMargin = 'm-0' | 'm-1' | 'm-2' | 'm-3' | 'm-4' | 'm-5' | 'm-6' | 'm-7' | 'm-8' | 'm-9' | 'm-10' | 'm-11' | 'm-12' | 'm-14' | 'm-16' | 'm-20' | 'm-24' | 'm-28' | 'm-32' | 'm-36' | 'm-40' | 'm-44' | 'm-48' | 'm-52' | 'm-56' | 'm-60' | 'm-64' | 'm-72' | 'm-80' | 'm-96' | 'm-px' | 'm-0.5' | 'm-1.5' | 'm-2.5' | 'm-3.5' | 'm-auto' | 'my-0' | 'my-1' | 'my-2' | 'my-3' | 'my-4' | 'my-5' | 'my-6' | 'my-7' | 'my-8' | 'my-9' | 'my-10' | 'my-11' | 'my-12' | 'my-14' | 'my-16' | 'my-20' | 'my-24' | 'my-28' | 'my-32' | 'my-36' | 'my-40' | 'my-44' | 'my-48' | 'my-52' | 'my-56' | 'my-60' | 'my-64' | 'my-72' | 'my-80' | 'my-96' | 'my-px' | 'my-0.5' | 'my-1.5' | 'my-2.5' | 'my-3.5' | 'my-auto' | 'mx-0' | 'mx-1' | 'mx-2' | 'mx-3' | 'mx-4' | 'mx-5' | 'mx-6' | 'mx-7' | 'mx-8' | 'mx-9' | 'mx-10' | 'mx-11' | 'mx-12' | 'mx-14' | 'mx-16' | 'mx-20' | 'mx-24' | 'mx-28' | 'mx-32' | 'mx-36' | 'mx-40' | 'mx-44' | 'mx-48' | 'mx-52' | 'mx-56' | 'mx-60' | 'mx-64' | 'mx-72' | 'mx-80' | 'mx-96' | 'mx-px' | 'mx-0.5' | 'mx-1.5' | 'mx-2.5' | 'mx-3.5' | 'mx-auto' | 'mt-0' | 'mt-1' | 'mt-2' | 'mt-3' | 'mt-4' | 'mt-5' | 'mt-6' | 'mt-7' | 'mt-8' | 'mt-9' | 'mt-10' | 'mt-11' | 'mt-12' | 'mt-14' | 'mt-16' | 'mt-20' | 'mt-24' | 'mt-28' | 'mt-32' | 'mt-36' | 'mt-40' | 'mt-44' | 'mt-48' | 'mt-52' | 'mt-56' | 'mt-60' | 'mt-64' | 'mt-72' | 'mt-80' | 'mt-96' | 'mt-px' | 'mt-0.5' | 'mt-1.5' | 'mt-2.5' | 'mt-3.5' | 'mt-auto' | 'mr-0' | 'mr-1' | 'mr-2' | 'mr-3' | 'mr-4' | 'mr-5' | 'mr-6' | 'mr-7' | 'mr-8' | 'mr-9' | 'mr-10' | 'mr-11' | 'mr-12' | 'mr-14' | 'mr-16' | 'mr-20' | 'mr-24' | 'mr-28' | 'mr-32' | 'mr-36' | 'mr-40' | 'mr-44' | 'mr-48' | 'mr-52' | 'mr-56' | 'mr-60' | 'mr-64' | 'mr-72' | 'mr-80' | 'mr-96' | 'mr-px' | 'mr-0.5' | 'mr-1.5' | 'mr-2.5' | 'mr-3.5' | 'mr-auto' | 'mb-0' | 'mb-1' | 'mb-2' | 'mb-3' | 'mb-4' | 'mb-5' | 'mb-6' | 'mb-7' | 'mb-8' | 'mb-9' | 'mb-10' | 'mb-11' | 'mb-12' | 'mb-14' | 'mb-16' | 'mb-20' | 'mb-24' | 'mb-28' | 'mb-32' | 'mb-36' | 'mb-40' | 'mb-44' | 'mb-48' | 'mb-52' | 'mb-56' | 'mb-60' | 'mb-64' | 'mb-72' | 'mb-80' | 'mb-96' | 'mb-px' | 'mb-0.5' | 'mb-1.5' | 'mb-2.5' | 'mb-3.5' | 'mb-auto' | 'ml-0' | 'ml-1' | 'ml-2' | 'ml-3' | 'ml-4' | 'ml-5' | 'ml-6' | 'ml-7' | 'ml-8' | 'ml-9' | 'ml-10' | 'ml-11' | 'ml-12' | 'ml-14' | 'ml-16' | 'ml-20' | 'ml-24' | 'ml-28' | 'ml-32' | 'ml-36' | 'ml-40' | 'ml-44' | 'ml-48' | 'ml-52' | 'ml-56' | 'ml-60' | 'ml-64' | 'ml-72' | 'ml-80' | 'ml-96' | 'ml-px' | 'ml-0.5' | 'ml-1.5' | 'ml-2.5' | 'ml-3.5' | 'ml-auto';
export declare type TSpace = 'space-x-0' | 'space-x-1' | 'space-x-2' | 'space-x-3' | 'space-x-4' | 'space-x-5' | 'space-x-6' | 'space-x-7' | 'space-x-8' | 'space-x-9' | 'space-x-10' | 'space-x-11' | 'space-x-12' | 'space-x-14' | 'space-x-16' | 'space-x-20' | 'space-x-24' | 'space-x-28' | 'space-x-32' | 'space-x-36' | 'space-x-40' | 'space-x-44' | 'space-x-48' | 'space-x-52' | 'space-x-56' | 'space-x-60' | 'space-x-64' | 'space-x-72' | 'space-x-80' | 'space-x-96' | 'space-x-px' | 'space-x-0.5' | 'space-x-1.5' | 'space-x-2.5' | 'space-x-3.5' | 'space-x-reverse' | 'space-y-0' | 'space-y-1' | 'space-y-2' | 'space-y-3' | 'space-y-4' | 'space-y-5' | 'space-y-6' | 'space-y-7' | 'space-y-8' | 'space-y-9' | 'space-y-10' | 'space-y-11' | 'space-y-12' | 'space-y-14' | 'space-y-16' | 'space-y-20' | 'space-y-24' | 'space-y-28' | 'space-y-32' | 'space-y-36' | 'space-y-40' | 'space-y-44' | 'space-y-48' | 'space-y-52' | 'space-y-56' | 'space-y-60' | 'space-y-64' | 'space-y-72' | 'space-y-80' | 'space-y-96' | 'space-y-px' | 'space-y-0.5' | 'space-y-1.5' | 'space-y-2.5' | 'space-y-3.5' | 'space-y-reverse';
export declare type TSpacing = TPadding | TMargin | TSpace;
export declare type TAppearance = 'appearance-none';
export declare type TPointerEvents = 'pointer-events-none' | 'pointer-events-auto';
export declare type TResize = 'resize-none' | 'resize' | 'resize-y' | 'resize-x';
export declare type TUserSelect = 'select-none' | 'select-text' | 'select-all' | 'select-auto';
export declare type TScrollSnap = 'snap-start' | 'snap-end' | 'snap-center' | 'snap-align-none' | 'snap-normal' | 'snap-always' | 'snap-none' | 'snap-x' | 'snap-y' | 'snap-both' | 'snap-mandatory' | 'snap-proximity';
export declare type TScrollBehavior = 'scroll-auto' | 'scroll-smooth';
export declare type TTouchAction = 'touch-auto' | 'touch-none' | 'touch-pan-x' | 'touch-pan-left' | 'touch-pan-right' | 'touch-pan-y' | 'touch-pan-up' | 'touch-pan-down' | 'touch-pinch-zoom' | 'touch-manipulation';
export declare type TCursor = 'cursor-auto' | 'cursor-default' | 'cursor-pointer' | 'cursor-wait' | 'cursor-text' | 'cursor-move' | 'cursor-help' | 'cursor-not-allowed' | 'cursor-none' | 'cursor-context-menu' | 'cursor-progress' | 'cursor-cell' | 'cursor-crosshair' | 'cursor-vertical-text' | 'cursor-alias' | 'cursor-copy' | 'cursor-no-drop' | 'cursor-grab' | 'cursor-grabbing' | 'cursor-all-scroll' | 'cursor-col-resize' | 'cursor-row-resize' | 'cursor-n-resize' | 'cursor-e-resize' | 'cursor-s-resize' | 'cursor-w-resize' | 'cursor-ne-resize' | 'cursor-nw-resize' | 'cursor-se-resize' | 'cursor-sw-resize' | 'cursor-ew-resize' | 'cursor-ns-resize' | 'cursor-nesw-resize' | 'cursor-nwse-resize' | 'cursor-zoom-in' | 'cursor-zoom-out';
export declare type TCaretColor = 'caret-current' | 'caret-transparent' | 'caret-lighten-100' | 'caret-darken-100' | 'caret-code' | 'caret-primary' | 'caret-primary-tint' | 'caret-primary-light' | 'caret-primary-dark' | 'caret-primary-darker' | 'caret-secondary' | 'caret-secondary-tint' | 'caret-secondary-light' | 'caret-secondary-dark' | 'caret-secondary-darker' | 'caret-success' | 'caret-success-tint' | 'caret-success-light' | 'caret-success-dark' | 'caret-success-darker' | 'caret-warning' | 'caret-warning-tint' | 'caret-warning-light' | 'caret-warning-dark' | 'caret-warning-darker' | 'caret-danger' | 'caret-danger-tint' | 'caret-danger-light' | 'caret-danger-dark' | 'caret-danger-darker' | 'caret-on-code' | 'caret-on-primary' | 'caret-on-success' | 'caret-on-warning' | 'caret-on-danger';
export declare type TWillChange = 'will-change-auto' | 'will-change-scroll' | 'will-change-contents' | 'will-change-transform';
export declare type TAccentColor = 'accent-current' | 'accent-transparent' | 'accent-lighten-100' | 'accent-darken-100' | 'accent-code' | 'accent-primary' | 'accent-primary-tint' | 'accent-primary-light' | 'accent-primary-dark' | 'accent-primary-darker' | 'accent-secondary' | 'accent-secondary-tint' | 'accent-secondary-light' | 'accent-secondary-dark' | 'accent-secondary-darker' | 'accent-success' | 'accent-success-tint' | 'accent-success-light' | 'accent-success-dark' | 'accent-success-darker' | 'accent-warning' | 'accent-warning-tint' | 'accent-warning-light' | 'accent-warning-dark' | 'accent-warning-darker' | 'accent-danger' | 'accent-danger-tint' | 'accent-danger-light' | 'accent-danger-dark' | 'accent-danger-darker' | 'accent-on-code' | 'accent-on-primary' | 'accent-on-success' | 'accent-on-warning' | 'accent-on-danger' | 'accent-auto';
export declare type TScrollPadding = 'scroll-p-0' | 'scroll-p-1' | 'scroll-p-2' | 'scroll-p-3' | 'scroll-p-4' | 'scroll-p-5' | 'scroll-p-6' | 'scroll-p-7' | 'scroll-p-8' | 'scroll-p-9' | 'scroll-p-10' | 'scroll-p-11' | 'scroll-p-12' | 'scroll-p-14' | 'scroll-p-16' | 'scroll-p-20' | 'scroll-p-24' | 'scroll-p-28' | 'scroll-p-32' | 'scroll-p-36' | 'scroll-p-40' | 'scroll-p-44' | 'scroll-p-48' | 'scroll-p-52' | 'scroll-p-56' | 'scroll-p-60' | 'scroll-p-64' | 'scroll-p-72' | 'scroll-p-80' | 'scroll-p-96' | 'scroll-p-px' | 'scroll-p-0.5' | 'scroll-p-1.5' | 'scroll-p-2.5' | 'scroll-p-3.5' | 'scroll-py-0' | 'scroll-py-1' | 'scroll-py-2' | 'scroll-py-3' | 'scroll-py-4' | 'scroll-py-5' | 'scroll-py-6' | 'scroll-py-7' | 'scroll-py-8' | 'scroll-py-9' | 'scroll-py-10' | 'scroll-py-11' | 'scroll-py-12' | 'scroll-py-14' | 'scroll-py-16' | 'scroll-py-20' | 'scroll-py-24' | 'scroll-py-28' | 'scroll-py-32' | 'scroll-py-36' | 'scroll-py-40' | 'scroll-py-44' | 'scroll-py-48' | 'scroll-py-52' | 'scroll-py-56' | 'scroll-py-60' | 'scroll-py-64' | 'scroll-py-72' | 'scroll-py-80' | 'scroll-py-96' | 'scroll-py-px' | 'scroll-py-0.5' | 'scroll-py-1.5' | 'scroll-py-2.5' | 'scroll-py-3.5' | 'scroll-px-0' | 'scroll-px-1' | 'scroll-px-2' | 'scroll-px-3' | 'scroll-px-4' | 'scroll-px-5' | 'scroll-px-6' | 'scroll-px-7' | 'scroll-px-8' | 'scroll-px-9' | 'scroll-px-10' | 'scroll-px-11' | 'scroll-px-12' | 'scroll-px-14' | 'scroll-px-16' | 'scroll-px-20' | 'scroll-px-24' | 'scroll-px-28' | 'scroll-px-32' | 'scroll-px-36' | 'scroll-px-40' | 'scroll-px-44' | 'scroll-px-48' | 'scroll-px-52' | 'scroll-px-56' | 'scroll-px-60' | 'scroll-px-64' | 'scroll-px-72' | 'scroll-px-80' | 'scroll-px-96' | 'scroll-px-px' | 'scroll-px-0.5' | 'scroll-px-1.5' | 'scroll-px-2.5' | 'scroll-px-3.5' | 'scroll-pt-0' | 'scroll-pt-1' | 'scroll-pt-2' | 'scroll-pt-3' | 'scroll-pt-4' | 'scroll-pt-5' | 'scroll-pt-6' | 'scroll-pt-7' | 'scroll-pt-8' | 'scroll-pt-9' | 'scroll-pt-10' | 'scroll-pt-11' | 'scroll-pt-12' | 'scroll-pt-14' | 'scroll-pt-16' | 'scroll-pt-20' | 'scroll-pt-24' | 'scroll-pt-28' | 'scroll-pt-32' | 'scroll-pt-36' | 'scroll-pt-40' | 'scroll-pt-44' | 'scroll-pt-48' | 'scroll-pt-52' | 'scroll-pt-56' | 'scroll-pt-60' | 'scroll-pt-64' | 'scroll-pt-72' | 'scroll-pt-80' | 'scroll-pt-96' | 'scroll-pt-px' | 'scroll-pt-0.5' | 'scroll-pt-1.5' | 'scroll-pt-2.5' | 'scroll-pt-3.5' | 'scroll-pr-0' | 'scroll-pr-1' | 'scroll-pr-2' | 'scroll-pr-3' | 'scroll-pr-4' | 'scroll-pr-5' | 'scroll-pr-6' | 'scroll-pr-7' | 'scroll-pr-8' | 'scroll-pr-9' | 'scroll-pr-10' | 'scroll-pr-11' | 'scroll-pr-12' | 'scroll-pr-14' | 'scroll-pr-16' | 'scroll-pr-20' | 'scroll-pr-24' | 'scroll-pr-28' | 'scroll-pr-32' | 'scroll-pr-36' | 'scroll-pr-40' | 'scroll-pr-44' | 'scroll-pr-48' | 'scroll-pr-52' | 'scroll-pr-56' | 'scroll-pr-60' | 'scroll-pr-64' | 'scroll-pr-72' | 'scroll-pr-80' | 'scroll-pr-96' | 'scroll-pr-px' | 'scroll-pr-0.5' | 'scroll-pr-1.5' | 'scroll-pr-2.5' | 'scroll-pr-3.5' | 'scroll-pb-0' | 'scroll-pb-1' | 'scroll-pb-2' | 'scroll-pb-3' | 'scroll-pb-4' | 'scroll-pb-5' | 'scroll-pb-6' | 'scroll-pb-7' | 'scroll-pb-8' | 'scroll-pb-9' | 'scroll-pb-10' | 'scroll-pb-11' | 'scroll-pb-12' | 'scroll-pb-14' | 'scroll-pb-16' | 'scroll-pb-20' | 'scroll-pb-24' | 'scroll-pb-28' | 'scroll-pb-32' | 'scroll-pb-36' | 'scroll-pb-40' | 'scroll-pb-44' | 'scroll-pb-48' | 'scroll-pb-52' | 'scroll-pb-56' | 'scroll-pb-60' | 'scroll-pb-64' | 'scroll-pb-72' | 'scroll-pb-80' | 'scroll-pb-96' | 'scroll-pb-px' | 'scroll-pb-0.5' | 'scroll-pb-1.5' | 'scroll-pb-2.5' | 'scroll-pb-3.5' | 'scroll-pl-0' | 'scroll-pl-1' | 'scroll-pl-2' | 'scroll-pl-3' | 'scroll-pl-4' | 'scroll-pl-5' | 'scroll-pl-6' | 'scroll-pl-7' | 'scroll-pl-8' | 'scroll-pl-9' | 'scroll-pl-10' | 'scroll-pl-11' | 'scroll-pl-12' | 'scroll-pl-14' | 'scroll-pl-16' | 'scroll-pl-20' | 'scroll-pl-24' | 'scroll-pl-28' | 'scroll-pl-32' | 'scroll-pl-36' | 'scroll-pl-40' | 'scroll-pl-44' | 'scroll-pl-48' | 'scroll-pl-52' | 'scroll-pl-56' | 'scroll-pl-60' | 'scroll-pl-64' | 'scroll-pl-72' | 'scroll-pl-80' | 'scroll-pl-96' | 'scroll-pl-px' | 'scroll-pl-0.5' | 'scroll-pl-1.5' | 'scroll-pl-2.5' | 'scroll-pl-3.5';
export declare type TScrollMargin = 'scroll-m-0' | 'scroll-m-1' | 'scroll-m-2' | 'scroll-m-3' | 'scroll-m-4' | 'scroll-m-5' | 'scroll-m-6' | 'scroll-m-7' | 'scroll-m-8' | 'scroll-m-9' | 'scroll-m-10' | 'scroll-m-11' | 'scroll-m-12' | 'scroll-m-14' | 'scroll-m-16' | 'scroll-m-20' | 'scroll-m-24' | 'scroll-m-28' | 'scroll-m-32' | 'scroll-m-36' | 'scroll-m-40' | 'scroll-m-44' | 'scroll-m-48' | 'scroll-m-52' | 'scroll-m-56' | 'scroll-m-60' | 'scroll-m-64' | 'scroll-m-72' | 'scroll-m-80' | 'scroll-m-96' | 'scroll-m-px' | 'scroll-m-0.5' | 'scroll-m-1.5' | 'scroll-m-2.5' | 'scroll-m-3.5' | 'scroll-my-0' | 'scroll-my-1' | 'scroll-my-2' | 'scroll-my-3' | 'scroll-my-4' | 'scroll-my-5' | 'scroll-my-6' | 'scroll-my-7' | 'scroll-my-8' | 'scroll-my-9' | 'scroll-my-10' | 'scroll-my-11' | 'scroll-my-12' | 'scroll-my-14' | 'scroll-my-16' | 'scroll-my-20' | 'scroll-my-24' | 'scroll-my-28' | 'scroll-my-32' | 'scroll-my-36' | 'scroll-my-40' | 'scroll-my-44' | 'scroll-my-48' | 'scroll-my-52' | 'scroll-my-56' | 'scroll-my-60' | 'scroll-my-64' | 'scroll-my-72' | 'scroll-my-80' | 'scroll-my-96' | 'scroll-my-px' | 'scroll-my-0.5' | 'scroll-my-1.5' | 'scroll-my-2.5' | 'scroll-my-3.5' | 'scroll-mx-0' | 'scroll-mx-1' | 'scroll-mx-2' | 'scroll-mx-3' | 'scroll-mx-4' | 'scroll-mx-5' | 'scroll-mx-6' | 'scroll-mx-7' | 'scroll-mx-8' | 'scroll-mx-9' | 'scroll-mx-10' | 'scroll-mx-11' | 'scroll-mx-12' | 'scroll-mx-14' | 'scroll-mx-16' | 'scroll-mx-20' | 'scroll-mx-24' | 'scroll-mx-28' | 'scroll-mx-32' | 'scroll-mx-36' | 'scroll-mx-40' | 'scroll-mx-44' | 'scroll-mx-48' | 'scroll-mx-52' | 'scroll-mx-56' | 'scroll-mx-60' | 'scroll-mx-64' | 'scroll-mx-72' | 'scroll-mx-80' | 'scroll-mx-96' | 'scroll-mx-px' | 'scroll-mx-0.5' | 'scroll-mx-1.5' | 'scroll-mx-2.5' | 'scroll-mx-3.5' | 'scroll-mt-0' | 'scroll-mt-1' | 'scroll-mt-2' | 'scroll-mt-3' | 'scroll-mt-4' | 'scroll-mt-5' | 'scroll-mt-6' | 'scroll-mt-7' | 'scroll-mt-8' | 'scroll-mt-9' | 'scroll-mt-10' | 'scroll-mt-11' | 'scroll-mt-12' | 'scroll-mt-14' | 'scroll-mt-16' | 'scroll-mt-20' | 'scroll-mt-24' | 'scroll-mt-28' | 'scroll-mt-32' | 'scroll-mt-36' | 'scroll-mt-40' | 'scroll-mt-44' | 'scroll-mt-48' | 'scroll-mt-52' | 'scroll-mt-56' | 'scroll-mt-60' | 'scroll-mt-64' | 'scroll-mt-72' | 'scroll-mt-80' | 'scroll-mt-96' | 'scroll-mt-px' | 'scroll-mt-0.5' | 'scroll-mt-1.5' | 'scroll-mt-2.5' | 'scroll-mt-3.5' | 'scroll-mr-0' | 'scroll-mr-1' | 'scroll-mr-2' | 'scroll-mr-3' | 'scroll-mr-4' | 'scroll-mr-5' | 'scroll-mr-6' | 'scroll-mr-7' | 'scroll-mr-8' | 'scroll-mr-9' | 'scroll-mr-10' | 'scroll-mr-11' | 'scroll-mr-12' | 'scroll-mr-14' | 'scroll-mr-16' | 'scroll-mr-20' | 'scroll-mr-24' | 'scroll-mr-28' | 'scroll-mr-32' | 'scroll-mr-36' | 'scroll-mr-40' | 'scroll-mr-44' | 'scroll-mr-48' | 'scroll-mr-52' | 'scroll-mr-56' | 'scroll-mr-60' | 'scroll-mr-64' | 'scroll-mr-72' | 'scroll-mr-80' | 'scroll-mr-96' | 'scroll-mr-px' | 'scroll-mr-0.5' | 'scroll-mr-1.5' | 'scroll-mr-2.5' | 'scroll-mr-3.5' | 'scroll-mb-0' | 'scroll-mb-1' | 'scroll-mb-2' | 'scroll-mb-3' | 'scroll-mb-4' | 'scroll-mb-5' | 'scroll-mb-6' | 'scroll-mb-7' | 'scroll-mb-8' | 'scroll-mb-9' | 'scroll-mb-10' | 'scroll-mb-11' | 'scroll-mb-12' | 'scroll-mb-14' | 'scroll-mb-16' | 'scroll-mb-20' | 'scroll-mb-24' | 'scroll-mb-28' | 'scroll-mb-32' | 'scroll-mb-36' | 'scroll-mb-40' | 'scroll-mb-44' | 'scroll-mb-48' | 'scroll-mb-52' | 'scroll-mb-56' | 'scroll-mb-60' | 'scroll-mb-64' | 'scroll-mb-72' | 'scroll-mb-80' | 'scroll-mb-96' | 'scroll-mb-px' | 'scroll-mb-0.5' | 'scroll-mb-1.5' | 'scroll-mb-2.5' | 'scroll-mb-3.5' | 'scroll-ml-0' | 'scroll-ml-1' | 'scroll-ml-2' | 'scroll-ml-3' | 'scroll-ml-4' | 'scroll-ml-5' | 'scroll-ml-6' | 'scroll-ml-7' | 'scroll-ml-8' | 'scroll-ml-9' | 'scroll-ml-10' | 'scroll-ml-11' | 'scroll-ml-12' | 'scroll-ml-14' | 'scroll-ml-16' | 'scroll-ml-20' | 'scroll-ml-24' | 'scroll-ml-28' | 'scroll-ml-32' | 'scroll-ml-36' | 'scroll-ml-40' | 'scroll-ml-44' | 'scroll-ml-48' | 'scroll-ml-52' | 'scroll-ml-56' | 'scroll-ml-60' | 'scroll-ml-64' | 'scroll-ml-72' | 'scroll-ml-80' | 'scroll-ml-96' | 'scroll-ml-px' | 'scroll-ml-0.5' | 'scroll-ml-1.5' | 'scroll-ml-2.5' | 'scroll-ml-3.5';
export declare type TInteractivity = TAppearance | TPointerEvents | TResize | TUserSelect | TScrollSnap | TScrollBehavior | TTouchAction | TCursor | TCaretColor | TWillChange | TAccentColor | TScrollPadding | TScrollMargin;
export declare type TDisplay = 'block' | 'inline-block' | 'inline' | 'flex' | 'inline-flex' | 'grid' | 'inline-grid' | 'table' | 'inline-table' | 'table-row' | 'table-cell' | 'contents' | 'list-item' | 'hidden';
export declare type TBoxDecorationBreak = 'box-decoration-slice' | 'box-decoration-clone';
export declare type TBoxSizing = 'box-border' | 'box-content';
export declare type TContainer = 'container';
export declare type TFloat = 'float-right' | 'float-left' | 'float-none';
export declare type TClear = 'clear-left' | 'clear-right' | 'clear-both' | 'clear-none';
export declare type TIsolation = 'isolate' | 'isolation-auto';
export declare type TObjectFit = 'object-contain' | 'object-cover' | 'object-fill' | 'object-none' | 'object-scale-down';
export declare type TOverflow = 'overflow-auto' | 'overflow-clip' | 'overflow-hidden' | 'overflow-visible' | 'overflow-scroll' | 'overflow-x-auto' | 'overflow-y-auto' | 'overflow-x-clip' | 'overflow-y-clip' | 'overflow-x-hidden' | 'overflow-y-hidden' | 'overflow-x-visible' | 'overflow-y-visible' | 'overflow-x-scroll' | 'overflow-y-scroll';
export declare type TOverscrollBehavior = 'overscroll-auto' | 'overscroll-contain' | 'overscroll-none' | 'overscroll-y-auto' | 'overscroll-y-contain' | 'overscroll-y-none' | 'overscroll-x-auto' | 'overscroll-x-contain' | 'overscroll-x-none';
export declare type TPosition = 'static' | 'fixed' | 'absolute' | 'relative' | 'sticky';
export declare type TVisibility = 'visible' | 'invisible';
export declare type TBreakBefore = 'break-before-auto' | 'break-before-avoid' | 'break-before-all' | 'break-before-avoid-page' | 'break-before-page' | 'break-before-left' | 'break-before-right' | 'break-before-column';
export declare type TBreakInside = 'break-inside-auto' | 'break-inside-avoid' | 'break-inside-avoid-page' | 'break-inside-avoid-column';
export declare type TBreakAfter = 'break-after-auto' | 'break-after-avoid' | 'break-after-all' | 'break-after-avoid-page' | 'break-after-page' | 'break-after-left' | 'break-after-right' | 'break-after-column';
export declare type TObjectPosition = 'object-bottom' | 'object-center' | 'object-left' | 'object-left-bottom' | 'object-left-top' | 'object-right' | 'object-right-bottom' | 'object-right-top' | 'object-top';
export declare type TInset = 'inset-0' | 'inset-x-0' | 'inset-y-0' | 'top-0' | 'right-0' | 'bottom-0' | 'left-0' | 'inset-1' | 'inset-x-1' | 'inset-y-1' | 'top-1' | 'right-1' | 'bottom-1' | 'left-1' | 'inset-2' | 'inset-x-2' | 'inset-y-2' | 'top-2' | 'right-2' | 'bottom-2' | 'left-2' | 'inset-3' | 'inset-x-3' | 'inset-y-3' | 'top-3' | 'right-3' | 'bottom-3' | 'left-3' | 'inset-4' | 'inset-x-4' | 'inset-y-4' | 'top-4' | 'right-4' | 'bottom-4' | 'left-4' | 'inset-5' | 'inset-x-5' | 'inset-y-5' | 'top-5' | 'right-5' | 'bottom-5' | 'left-5' | 'inset-6' | 'inset-x-6' | 'inset-y-6' | 'top-6' | 'right-6' | 'bottom-6' | 'left-6' | 'inset-7' | 'inset-x-7' | 'inset-y-7' | 'top-7' | 'right-7' | 'bottom-7' | 'left-7' | 'inset-8' | 'inset-x-8' | 'inset-y-8' | 'top-8' | 'right-8' | 'bottom-8' | 'left-8' | 'inset-9' | 'inset-x-9' | 'inset-y-9' | 'top-9' | 'right-9' | 'bottom-9' | 'left-9' | 'inset-10' | 'inset-x-10' | 'inset-y-10' | 'top-10' | 'right-10' | 'bottom-10' | 'left-10' | 'inset-11' | 'inset-x-11' | 'inset-y-11' | 'top-11' | 'right-11' | 'bottom-11' | 'left-11' | 'inset-12' | 'inset-x-12' | 'inset-y-12' | 'top-12' | 'right-12' | 'bottom-12' | 'left-12' | 'inset-14' | 'inset-x-14' | 'inset-y-14' | 'top-14' | 'right-14' | 'bottom-14' | 'left-14' | 'inset-16' | 'inset-x-16' | 'inset-y-16' | 'top-16' | 'right-16' | 'bottom-16' | 'left-16' | 'inset-20' | 'inset-x-20' | 'inset-y-20' | 'top-20' | 'right-20' | 'bottom-20' | 'left-20' | 'inset-24' | 'inset-x-24' | 'inset-y-24' | 'top-24' | 'right-24' | 'bottom-24' | 'left-24' | 'inset-28' | 'inset-x-28' | 'inset-y-28' | 'top-28' | 'right-28' | 'bottom-28' | 'left-28' | 'inset-32' | 'inset-x-32' | 'inset-y-32' | 'top-32' | 'right-32' | 'bottom-32' | 'left-32' | 'inset-36' | 'inset-x-36' | 'inset-y-36' | 'top-36' | 'right-36' | 'bottom-36' | 'left-36' | 'inset-40' | 'inset-x-40' | 'inset-y-40' | 'top-40' | 'right-40' | 'bottom-40' | 'left-40' | 'inset-44' | 'inset-x-44' | 'inset-y-44' | 'top-44' | 'right-44' | 'bottom-44' | 'left-44' | 'inset-48' | 'inset-x-48' | 'inset-y-48' | 'top-48' | 'right-48' | 'bottom-48' | 'left-48' | 'inset-52' | 'inset-x-52' | 'inset-y-52' | 'top-52' | 'right-52' | 'bottom-52' | 'left-52' | 'inset-56' | 'inset-x-56' | 'inset-y-56' | 'top-56' | 'right-56' | 'bottom-56' | 'left-56' | 'inset-60' | 'inset-x-60' | 'inset-y-60' | 'top-60' | 'right-60' | 'bottom-60' | 'left-60' | 'inset-64' | 'inset-x-64' | 'inset-y-64' | 'top-64' | 'right-64' | 'bottom-64' | 'left-64' | 'inset-72' | 'inset-x-72' | 'inset-y-72' | 'top-72' | 'right-72' | 'bottom-72' | 'left-72' | 'inset-80' | 'inset-x-80' | 'inset-y-80' | 'top-80' | 'right-80' | 'bottom-80' | 'left-80' | 'inset-96' | 'inset-x-96' | 'inset-y-96' | 'top-96' | 'right-96' | 'bottom-96' | 'left-96' | 'inset-px' | 'inset-x-px' | 'inset-y-px' | 'top-px' | 'right-px' | 'bottom-px' | 'left-px' | 'inset-0.5' | 'inset-x-0.5' | 'inset-y-0.5' | 'top-0.5' | 'right-0.5' | 'bottom-0.5' | 'left-0.5' | 'inset-1.5' | 'inset-x-1.5' | 'inset-y-1.5' | 'top-1.5' | 'right-1.5' | 'bottom-1.5' | 'left-1.5' | 'inset-2.5' | 'inset-x-2.5' | 'inset-y-2.5' | 'top-2.5' | 'right-2.5' | 'bottom-2.5' | 'left-2.5' | 'inset-3.5' | 'inset-x-3.5' | 'inset-y-3.5' | 'top-3.5' | 'right-3.5' | 'bottom-3.5' | 'left-3.5' | 'inset-1/2' | 'inset-x-1/2' | 'inset-y-1/2' | 'top-1/2' | 'right-1/2' | 'bottom-1/2' | 'left-1/2' | 'inset-1/3' | 'inset-x-1/3' | 'inset-y-1/3' | 'top-1/3' | 'right-1/3' | 'bottom-1/3' | 'left-1/3' | 'inset-2/3' | 'inset-x-2/3' | 'inset-y-2/3' | 'top-2/3' | 'right-2/3' | 'bottom-2/3' | 'left-2/3' | 'inset-1/4' | 'inset-x-1/4' | 'inset-y-1/4' | 'top-1/4' | 'right-1/4' | 'bottom-1/4' | 'left-1/4' | 'inset-2/4' | 'inset-x-2/4' | 'inset-y-2/4' | 'top-2/4' | 'right-2/4' | 'bottom-2/4' | 'left-2/4' | 'inset-3/4' | 'inset-x-3/4' | 'inset-y-3/4' | 'top-3/4' | 'right-3/4' | 'bottom-3/4' | 'left-3/4' | 'inset-auto' | 'inset-x-auto' | 'inset-y-auto' | 'top-auto' | 'right-auto' | 'bottom-auto' | 'left-auto' | 'inset-full' | 'inset-x-full' | 'inset-y-full' | 'top-full' | 'right-full' | 'bottom-full' | 'left-full';
export declare type TZIndex = 'z-0' | 'z-10' | 'z-20' | 'z-30' | 'z-40' | 'z-50' | 'z-auto' | '-z-1';
export declare type TAspectRatio = 'aspect-auto' | 'aspect-square' | 'aspect-video';
export declare type TColumns = 'columns-auto' | 'columns-3xs' | 'columns-2xs' | 'columns-xs' | 'columns-sm' | 'columns-md' | 'columns-lg' | 'columns-xl' | 'columns-2xl' | 'columns-3xl' | 'columns-4xl' | 'columns-5xl' | 'columns-6xl' | 'columns-7xl';
export declare type TLayout = TDisplay | TBoxDecorationBreak | TBoxSizing | TContainer | TFloat | TClear | TIsolation | TObjectFit | TOverflow | TOverscrollBehavior | TPosition | TVisibility | TBreakBefore | TBreakInside | TBreakAfter | TObjectPosition | TInset | TZIndex | TAspectRatio | TColumns;
export declare type TWidth = 'w-0' | 'w-1' | 'w-2' | 'w-3' | 'w-4' | 'w-5' | 'w-6' | 'w-7' | 'w-8' | 'w-9' | 'w-10' | 'w-11' | 'w-12' | 'w-14' | 'w-16' | 'w-20' | 'w-24' | 'w-28' | 'w-32' | 'w-36' | 'w-40' | 'w-44' | 'w-48' | 'w-52' | 'w-56' | 'w-60' | 'w-64' | 'w-72' | 'w-80' | 'w-96' | 'w-px' | 'w-0.5' | 'w-1.5' | 'w-2.5' | 'w-3.5' | 'w-1/2' | 'w-1/3' | 'w-2/3' | 'w-1/4' | 'w-2/4' | 'w-3/4' | 'w-1/5' | 'w-2/5' | 'w-3/5' | 'w-4/5' | 'w-1/6' | 'w-2/6' | 'w-3/6' | 'w-4/6' | 'w-5/6' | 'w-1/12' | 'w-2/12' | 'w-3/12' | 'w-4/12' | 'w-5/12' | 'w-6/12' | 'w-7/12' | 'w-8/12' | 'w-9/12' | 'w-10/12' | 'w-11/12' | 'w-auto' | 'w-full' | 'w-min' | 'w-max' | 'w-fit' | 'w-screen' | 'w-xs' | 'w-sm' | 'w-md' | 'w-lg' | 'w-xl' | 'w-2xl' | 'w-3xl';
export declare type TMinWidth = 'min-w-0' | 'min-w-full' | 'min-w-min' | 'min-w-max' | 'min-w-fit';
export declare type TMaxWidth = 'max-w-0' | 'max-w-screen-lg' | 'max-w-screen-md' | 'max-w-screen-sm' | 'max-w-none' | 'max-w-xs' | 'max-w-sm' | 'max-w-md' | 'max-w-lg' | 'max-w-xl' | 'max-w-2xl' | 'max-w-3xl' | 'max-w-4xl' | 'max-w-5xl' | 'max-w-6xl' | 'max-w-7xl' | 'max-w-full' | 'max-w-min' | 'max-w-max' | 'max-w-fit' | 'max-w-prose';
export declare type THeight = 'h-0' | 'h-1' | 'h-2' | 'h-3' | 'h-4' | 'h-5' | 'h-6' | 'h-7' | 'h-8' | 'h-9' | 'h-10' | 'h-11' | 'h-12' | 'h-14' | 'h-16' | 'h-20' | 'h-24' | 'h-28' | 'h-32' | 'h-36' | 'h-40' | 'h-44' | 'h-48' | 'h-52' | 'h-56' | 'h-60' | 'h-64' | 'h-72' | 'h-80' | 'h-96' | 'h-px' | 'h-0.5' | 'h-1.5' | 'h-2.5' | 'h-3.5' | 'h-1/2' | 'h-1/3' | 'h-2/3' | 'h-1/4' | 'h-2/4' | 'h-3/4' | 'h-1/5' | 'h-2/5' | 'h-3/5' | 'h-4/5' | 'h-1/6' | 'h-2/6' | 'h-3/6' | 'h-4/6' | 'h-5/6' | 'h-auto' | 'h-full' | 'h-screen' | 'h-xs' | 'h-sm' | 'h-md' | 'h-lg' | 'h-xl' | 'h-2xl' | 'h-3xl';
export declare type TMinHeight = 'min-h-0' | 'min-h-full' | 'min-h-min' | 'min-h-max' | 'min-h-fit' | 'min-h-screen';
export declare type TMaxHeight = 'max-h-0' | 'max-h-1' | 'max-h-2' | 'max-h-3' | 'max-h-4' | 'max-h-5' | 'max-h-6' | 'max-h-7' | 'max-h-8' | 'max-h-9' | 'max-h-10' | 'max-h-11' | 'max-h-12' | 'max-h-14' | 'max-h-16' | 'max-h-20' | 'max-h-24' | 'max-h-28' | 'max-h-32' | 'max-h-36' | 'max-h-40' | 'max-h-44' | 'max-h-48' | 'max-h-52' | 'max-h-56' | 'max-h-60' | 'max-h-64' | 'max-h-72' | 'max-h-80' | 'max-h-96' | 'max-h-px' | 'max-h-0.5' | 'max-h-1.5' | 'max-h-2.5' | 'max-h-3.5' | 'max-h-full' | 'max-h-min' | 'max-h-max' | 'max-h-fit' | 'max-h-screen';
export declare type TSizing = TWidth | TMinWidth | TMaxWidth | THeight | TMinHeight | TMaxHeight;
export declare type TFill = 'fill-current' | 'fill-transparent' | 'fill-lighten-100' | 'fill-darken-100' | 'fill-code' | 'fill-primary' | 'fill-primary-tint' | 'fill-primary-light' | 'fill-primary-dark' | 'fill-primary-darker' | 'fill-secondary' | 'fill-secondary-tint' | 'fill-secondary-light' | 'fill-secondary-dark' | 'fill-secondary-darker' | 'fill-success' | 'fill-success-tint' | 'fill-success-light' | 'fill-success-dark' | 'fill-success-darker' | 'fill-warning' | 'fill-warning-tint' | 'fill-warning-light' | 'fill-warning-dark' | 'fill-warning-darker' | 'fill-danger' | 'fill-danger-tint' | 'fill-danger-light' | 'fill-danger-dark' | 'fill-danger-darker' | 'fill-on-code' | 'fill-on-primary' | 'fill-on-success' | 'fill-on-warning' | 'fill-on-danger' | 'fill';
export declare type TStroke = 'stroke-current' | 'stroke-transparent' | 'stroke-lighten-100' | 'stroke-darken-100' | 'stroke-code' | 'stroke-primary' | 'stroke-primary-tint' | 'stroke-primary-light' | 'stroke-primary-dark' | 'stroke-primary-darker' | 'stroke-secondary' | 'stroke-secondary-tint' | 'stroke-secondary-light' | 'stroke-secondary-dark' | 'stroke-secondary-darker' | 'stroke-success' | 'stroke-success-tint' | 'stroke-success-light' | 'stroke-success-dark' | 'stroke-success-darker' | 'stroke-warning' | 'stroke-warning-tint' | 'stroke-warning-light' | 'stroke-warning-dark' | 'stroke-warning-darker' | 'stroke-danger' | 'stroke-danger-tint' | 'stroke-danger-light' | 'stroke-danger-dark' | 'stroke-danger-darker' | 'stroke-on-code' | 'stroke-on-primary' | 'stroke-on-success' | 'stroke-on-warning' | 'stroke-on-danger' | 'stroke-text';
export declare type TStrokeWidth = 'stroke-0' | 'stroke-1' | 'stroke-2';
export declare type TSVG = TFill | TStroke | TStrokeWidth;
export declare type THardwareAcceleration = 'transform-gpu';
export declare type TScale = 'scale-0' | 'scale-50' | 'scale-75' | 'scale-90' | 'scale-95' | 'scale-100' | 'scale-105' | 'scale-110' | 'scale-125' | 'scale-150' | 'scale-x-0' | 'scale-x-50' | 'scale-x-75' | 'scale-x-90' | 'scale-x-95' | 'scale-x-100' | 'scale-x-105' | 'scale-x-110' | 'scale-x-125' | 'scale-x-150' | 'scale-y-0' | 'scale-y-50' | 'scale-y-75' | 'scale-y-90' | 'scale-y-95' | 'scale-y-100' | 'scale-y-105' | 'scale-y-110' | 'scale-y-125' | 'scale-y-150';
export declare type TRotate = 'rotate-0' | 'rotate-1' | 'rotate-2' | 'rotate-3' | 'rotate-6' | 'rotate-12' | 'rotate-45' | 'rotate-90' | 'rotate-180';
export declare type TTranslate = 'translate-x-0' | 'translate-x-1' | 'translate-x-2' | 'translate-x-3' | 'translate-x-4' | 'translate-x-5' | 'translate-x-6' | 'translate-x-7' | 'translate-x-8' | 'translate-x-9' | 'translate-x-10' | 'translate-x-11' | 'translate-x-12' | 'translate-x-14' | 'translate-x-16' | 'translate-x-20' | 'translate-x-24' | 'translate-x-28' | 'translate-x-32' | 'translate-x-36' | 'translate-x-40' | 'translate-x-44' | 'translate-x-48' | 'translate-x-52' | 'translate-x-56' | 'translate-x-60' | 'translate-x-64' | 'translate-x-72' | 'translate-x-80' | 'translate-x-96' | 'translate-x-px' | 'translate-x-0.5' | 'translate-x-1.5' | 'translate-x-2.5' | 'translate-x-3.5' | 'translate-x-1/2' | 'translate-x-1/3' | 'translate-x-2/3' | 'translate-x-1/4' | 'translate-x-2/4' | 'translate-x-3/4' | 'translate-x-full' | 'translate-y-0' | 'translate-y-1' | 'translate-y-2' | 'translate-y-3' | 'translate-y-4' | 'translate-y-5' | 'translate-y-6' | 'translate-y-7' | 'translate-y-8' | 'translate-y-9' | 'translate-y-10' | 'translate-y-11' | 'translate-y-12' | 'translate-y-14' | 'translate-y-16' | 'translate-y-20' | 'translate-y-24' | 'translate-y-28' | 'translate-y-32' | 'translate-y-36' | 'translate-y-40' | 'translate-y-44' | 'translate-y-48' | 'translate-y-52' | 'translate-y-56' | 'translate-y-60' | 'translate-y-64' | 'translate-y-72' | 'translate-y-80' | 'translate-y-96' | 'translate-y-px' | 'translate-y-0.5' | 'translate-y-1.5' | 'translate-y-2.5' | 'translate-y-3.5' | 'translate-y-1/2' | 'translate-y-1/3' | 'translate-y-2/3' | 'translate-y-1/4' | 'translate-y-2/4' | 'translate-y-3/4' | 'translate-y-full';
export declare type TSkew = 'skew-x-0' | 'skew-x-1' | 'skew-x-2' | 'skew-x-3' | 'skew-x-6' | 'skew-x-12' | 'skew-y-0' | 'skew-y-1' | 'skew-y-2' | 'skew-y-3' | 'skew-y-6' | 'skew-y-12';
export declare type TTransformOrigin = 'origin-center' | 'origin-top' | 'origin-top-right' | 'origin-right' | 'origin-bottom-right' | 'origin-bottom' | 'origin-bottom-left' | 'origin-left' | 'origin-top-left';
export declare type TTransforms = THardwareAcceleration | TScale | TRotate | TTranslate | TSkew | TTransformOrigin;
export declare type TFontSmoothing = 'antialiased' | 'subpixel-antialiased';
export declare type TFontStyle = 'italic' | 'non-italic';
export declare type TFontVariantNumeric = 'normal-nums' | 'ordinal' | 'slashed-zero' | 'lining-nums' | 'oldstyle-nums' | 'proportional-nums' | 'tabular-nums' | 'diagonal-fractions' | 'stacked-fractions';
export declare type TListStylePosition = 'list-inside' | 'list-outside';
export declare type TTextAlign = 'text-left' | 'text-center' | 'text-right' | 'text-justify';
export declare type TTextDecoration = 'underline' | 'line-through' | 'no-underline';
export declare type TTextTransform = 'uppercase' | 'lowercase' | 'capitalize' | 'normal-case';
export declare type TTextOverflow = 'truncate' | 'text-ellipsis' | 'text-clip';
export declare type TVerticalAlign = 'align-baseline' | 'align-top' | 'align-middle' | 'align-bottom' | 'align-text-top' | 'align-text-bottom' | 'align-sub' | 'align-super';
export declare type TWhitespace = 'whitespace-normal' | 'whitespace-nowrap' | 'whitespace-pre' | 'whitespace-pre-line' | 'whitespace-pre-wrap';
export declare type TWordBreak = 'break-normal' | 'break-words' | 'break-all';
export declare type TTextDecorationStyle = 'decoration-solid' | 'decoration-double' | 'decoration-dotted' | 'decoration-dashed' | 'decoration-wavy';
export declare type TFontFamily = 'font-sans' | 'font-ui' | 'font-prose' | 'font-mono';
export declare type TFontSize = 'text-2xs' | 'text-xs' | 'text-sm' | 'text-base' | 'text-lg' | 'text-xl' | 'text-2xl' | 'text-3xl' | 'text-4xl' | 'text-5xl' | 'text-6xl' | 'text-7xl' | 'text-8xl' | 'text-9xl' | 'text-paragraph-leading' | 'text-paragraph' | 'text-paragraph-small' | 'text-paragraph-tiny';
export declare type TFontWeight = 'font-light' | 'font-normal' | 'font-medium' | 'font-semibold' | 'font-bold';
export declare type TLetterSpacing = 'tracking-tighter' | 'tracking-tight' | 'tracking-normal' | 'tracking-wide' | 'tracking-wider' | 'tracking-widest';
export declare type TLineHeight = 'leading-3' | 'leading-4' | 'leading-5' | 'leading-6' | 'leading-7' | 'leading-8' | 'leading-9' | 'leading-10' | 'leading-none' | 'leading-tight' | 'leading-snug' | 'leading-normal' | 'leading-relaxed' | 'leading-loose' | 'leading-zero' | 'leading-paragraph-leading' | 'leading-paragraph' | 'leading-paragraph-small' | 'leading-paragraph-tiny';
export declare type TListStyleType = 'list-none' | 'list-disc' | 'list-decimal';
export declare type TPlaceholderColor = 'placeholder-current' | 'placeholder-transparent' | 'placeholder-lighten-100' | 'placeholder-darken-100' | 'placeholder-code' | 'placeholder-primary' | 'placeholder-primary-tint' | 'placeholder-primary-light' | 'placeholder-primary-dark' | 'placeholder-primary-darker' | 'placeholder-secondary' | 'placeholder-secondary-tint' | 'placeholder-secondary-light' | 'placeholder-secondary-dark' | 'placeholder-secondary-darker' | 'placeholder-success' | 'placeholder-success-tint' | 'placeholder-success-light' | 'placeholder-success-dark' | 'placeholder-success-darker' | 'placeholder-warning' | 'placeholder-warning-tint' | 'placeholder-warning-light' | 'placeholder-warning-dark' | 'placeholder-warning-darker' | 'placeholder-danger' | 'placeholder-danger-tint' | 'placeholder-danger-light' | 'placeholder-danger-dark' | 'placeholder-danger-darker' | 'placeholder-on-code' | 'placeholder-on-primary' | 'placeholder-on-success' | 'placeholder-on-warning' | 'placeholder-on-danger';
export declare type TPlaceholderOpacity = 'placeholder-opacity-0' | 'placeholder-opacity-5' | 'placeholder-opacity-10' | 'placeholder-opacity-20' | 'placeholder-opacity-25' | 'placeholder-opacity-30' | 'placeholder-opacity-40' | 'placeholder-opacity-50' | 'placeholder-opacity-60' | 'placeholder-opacity-70' | 'placeholder-opacity-75' | 'placeholder-opacity-80' | 'placeholder-opacity-90' | 'placeholder-opacity-95' | 'placeholder-opacity-100';
export declare type TTextColor = 'text-current' | 'text-transparent' | 'text-lighten-100' | 'text-darken-100' | 'text-code' | 'text-primary' | 'text-primary-tint' | 'text-primary-light' | 'text-primary-dark' | 'text-primary-darker' | 'text-secondary' | 'text-secondary-tint' | 'text-secondary-light' | 'text-secondary-dark' | 'text-secondary-darker' | 'text-success' | 'text-success-tint' | 'text-success-light' | 'text-success-dark' | 'text-success-darker' | 'text-warning' | 'text-warning-tint' | 'text-warning-light' | 'text-warning-dark' | 'text-warning-darker' | 'text-danger' | 'text-danger-tint' | 'text-danger-light' | 'text-danger-dark' | 'text-danger-darker' | 'text-on-code' | 'text-on-primary' | 'text-on-success' | 'text-on-warning' | 'text-on-danger' | 'text-body' | 'text-muted' | 'text-light' | 'text-heading' | 'text-paragraph' | 'text-canvas-pure' | 'text-canvas' | 'text-canvas-50' | 'text-canvas-100' | 'text-canvas-200' | 'text-canvas-300' | 'text-canvas-dialog' | 'text-link' | 'text-link-dark';
export declare type TTextOpacity = 'text-opacity-0' | 'text-opacity-5' | 'text-opacity-10' | 'text-opacity-20' | 'text-opacity-25' | 'text-opacity-30' | 'text-opacity-40' | 'text-opacity-50' | 'text-opacity-60' | 'text-opacity-70' | 'text-opacity-75' | 'text-opacity-80' | 'text-opacity-90' | 'text-opacity-95' | 'text-opacity-100';
export declare type TContent = 'content-none';
export declare type TTextIndent = 'indent-0' | 'indent-1' | 'indent-2' | 'indent-3' | 'indent-4' | 'indent-5' | 'indent-6' | 'indent-7' | 'indent-8' | 'indent-9' | 'indent-10' | 'indent-11' | 'indent-12' | 'indent-14' | 'indent-16' | 'indent-20' | 'indent-24' | 'indent-28' | 'indent-32' | 'indent-36' | 'indent-40' | 'indent-44' | 'indent-48' | 'indent-52' | 'indent-56' | 'indent-60' | 'indent-64' | 'indent-72' | 'indent-80' | 'indent-96' | 'indent-px' | 'indent-0.5' | 'indent-1.5' | 'indent-2.5' | 'indent-3.5';
export declare type TTextDecorationColor = 'decoration-current' | 'decoration-transparent' | 'decoration-lighten-100' | 'decoration-darken-100' | 'decoration-code' | 'decoration-primary' | 'decoration-primary-tint' | 'decoration-primary-light' | 'decoration-primary-dark' | 'decoration-primary-darker' | 'decoration-secondary' | 'decoration-secondary-tint' | 'decoration-secondary-light' | 'decoration-secondary-dark' | 'decoration-secondary-darker' | 'decoration-success' | 'decoration-success-tint' | 'decoration-success-light' | 'decoration-success-dark' | 'decoration-success-darker' | 'decoration-warning' | 'decoration-warning-tint' | 'decoration-warning-light' | 'decoration-warning-dark' | 'decoration-warning-darker' | 'decoration-danger' | 'decoration-danger-tint' | 'decoration-danger-light' | 'decoration-danger-dark' | 'decoration-danger-darker' | 'decoration-on-code' | 'decoration-on-primary' | 'decoration-on-success' | 'decoration-on-warning' | 'decoration-on-danger';
export declare type TTextDecorationThickness = 'decoration-0' | 'decoration-1' | 'decoration-2' | 'decoration-4' | 'decoration-8' | 'decoration-from-font' | 'decoration-auto';
export declare type TTextUnderlineOffset = 'underline-offset-0' | 'underline-offset-1' | 'underline-offset-2' | 'underline-offset-4' | 'underline-offset-8' | 'underline-offset-auto';
export declare type TTypography = TFontSmoothing | TFontStyle | TFontVariantNumeric | TListStylePosition | TTextAlign | TTextDecoration | TTextTransform | TTextOverflow | TVerticalAlign | TWhitespace | TWordBreak | TTextDecorationStyle | TFontFamily | TFontSize | TFontWeight | TLetterSpacing | TLineHeight | TListStyleType | TPlaceholderColor | TPlaceholderOpacity | TTextColor | TTextOpacity | TContent | TTextIndent | TTextDecorationColor | TTextDecorationThickness | TTextUnderlineOffset;
export declare type TPseudoClassVariants = 'motion-safe:' | 'motion-reduce:' | 'first:' | 'last:' | 'odd:' | 'even:' | 'visited:' | 'checked:' | 'group:' | 'group-hover:' | 'group-focus:' | 'focus-within:' | 'hover:' | 'focus:' | 'focus-visible:' | 'active:' | 'disabled:' | 'only:' | 'first-of-type:' | 'last-of-type:' | 'only-of-type:' | 'target:' | 'default:' | 'indeterminate:' | 'placeholder-shown:' | 'autofill:' | 'required:' | 'valid:' | 'invalid:' | 'in-range:' | 'out-of-range:' | 'peer:' | 'peer-hover:' | 'peer-checked:' | 'peer-focus:' | 'selection:' | 'marker:' | 'before:' | 'after:' | 'portrait:' | 'landscape:' | 'open:' | 'file:' | 'placeholder:' | 'print:' | 'ltr:' | 'rtl:' | 'lg:' | 'md:' | 'sm:';
declare type TUtilityFunction<T extends string> = (...args: Array<T | `!${T}` | `${TPseudoClassVariants}${T}` | `${TPseudoClassVariants}!${T}` | null | undefined | {
    [key in T | `${TPseudoClassVariants}${T}` | `!${T}` | `${TPseudoClassVariants}!${T}` | TTailwindString]?: boolean;
} | TTailwindString>) => TTailwindString;
export declare const screenReaders: TUtilityFunction<TScreenReaders>;
export declare const backgroundAttachment: TUtilityFunction<TBackgroundAttachment>;
export declare const backgroundClip: TUtilityFunction<TBackgroundClip>;
export declare const backgroundOrigin: TUtilityFunction<TBackgroundOrigin>;
export declare const backgroundRepeat: TUtilityFunction<TBackgroundRepeat>;
export declare const backgroundOpacity: TUtilityFunction<TBackgroundOpacity>;
export declare const backgroundColor: TUtilityFunction<TBackgroundColor>;
export declare const backgroundPosition: TUtilityFunction<TBackgroundPosition>;
export declare const backgroundSize: TUtilityFunction<TBackgroundSize>;
export declare const backgroundImage: TUtilityFunction<TBackgroundImage>;
export declare const gradientColorStops: TUtilityFunction<TGradientColorStops>;
export declare const borderStyle: TUtilityFunction<TBorderStyle>;
export declare const divideStyle: TUtilityFunction<TDivideStyle>;
export declare const outlineStyle: TUtilityFunction<TOutlineStyle>;
export declare const borderColor: TUtilityFunction<TBorderColor>;
export declare const borderOpacity: TUtilityFunction<TBorderOpacity>;
export declare const borderRadius: TUtilityFunction<TBorderRadius>;
export declare const borderWidth: TUtilityFunction<TBorderWidth>;
export declare const divideColor: TUtilityFunction<TDivideColor>;
export declare const divideOpacity: TUtilityFunction<TDivideOpacity>;
export declare const divideWidth: TUtilityFunction<TDivideWidth>;
export declare const ringColor: TUtilityFunction<TRingColor>;
export declare const ringWidth: TUtilityFunction<TRingWidth>;
export declare const ringOpacity: TUtilityFunction<TRingOpacity>;
export declare const ringOffsetColor: TUtilityFunction<TRingOffsetColor>;
export declare const ringOffsetWidth: TUtilityFunction<TRingOffsetWidth>;
export declare const outlineOffset: TUtilityFunction<TOutlineOffset>;
export declare const outlineWidth: TUtilityFunction<TOutlineWidth>;
export declare const outlineColor: TUtilityFunction<TOutlineColor>;
export declare const borderCollapse: TUtilityFunction<TBorderCollapse>;
export declare const tableLayout: TUtilityFunction<TTableLayout>;
export declare const mixBlendMode: TUtilityFunction<TMixBlendMode>;
export declare const backgroundBlendMode: TUtilityFunction<TBackgroundBlendMode>;
export declare const boxShadow: TUtilityFunction<TBoxShadow>;
export declare const boxShadowColor: TUtilityFunction<TBoxShadowColor>;
export declare const opacity: TUtilityFunction<TOpacity>;
export declare const transitionProperty: TUtilityFunction<TTransitionProperty>;
export declare const transitionDuration: TUtilityFunction<TTransitionDuration>;
export declare const transitionTimingFunction: TUtilityFunction<TTransitionTimingFunction>;
export declare const transitionDelay: TUtilityFunction<TTransitionDelay>;
export declare const animation: TUtilityFunction<TAnimation>;
export declare const filter: TUtilityFunction<TFilter>;
export declare const backdropFilter: TUtilityFunction<TBackdropFilter>;
export declare const blur: TUtilityFunction<TBlur>;
export declare const brightness: TUtilityFunction<TBrightness>;
export declare const contrast: TUtilityFunction<TContrast>;
export declare const dropShadow: TUtilityFunction<TDropShadow>;
export declare const grayscale: TUtilityFunction<TGrayscale>;
export declare const hueRotate: TUtilityFunction<THueRotate>;
export declare const invert: TUtilityFunction<TInvert>;
export declare const saturate: TUtilityFunction<TSaturate>;
export declare const sepia: TUtilityFunction<TSepia>;
export declare const backdropBlur: TUtilityFunction<TBackdropBlur>;
export declare const backdropBrightness: TUtilityFunction<TBackdropBrightness>;
export declare const backdropContrast: TUtilityFunction<TBackdropContrast>;
export declare const backdropGrayscale: TUtilityFunction<TBackdropGrayscale>;
export declare const backdropHueRotate: TUtilityFunction<TBackdropHueRotate>;
export declare const backdropInvert: TUtilityFunction<TBackdropInvert>;
export declare const backdropOpacity: TUtilityFunction<TBackdropOpacity>;
export declare const backdropSaturate: TUtilityFunction<TBackdropSaturate>;
export declare const backdropSepia: TUtilityFunction<TBackdropSepia>;
export declare const flexDirection: TUtilityFunction<TFlexDirection>;
export declare const flexWrap: TUtilityFunction<TFlexWrap>;
export declare const alignItems: TUtilityFunction<TAlignItems>;
export declare const alignContent: TUtilityFunction<TAlignContent>;
export declare const alignSelf: TUtilityFunction<TAlignSelf>;
export declare const placeContent: TUtilityFunction<TPlaceContent>;
export declare const placeItems: TUtilityFunction<TPlaceItems>;
export declare const placeSelf: TUtilityFunction<TPlaceSelf>;
export declare const justifyContent: TUtilityFunction<TJustifyContent>;
export declare const justifyItems: TUtilityFunction<TJustifyItems>;
export declare const justifySelf: TUtilityFunction<TJustifySelf>;
export declare const flex: TUtilityFunction<TFlex>;
export declare const flexBasis: TUtilityFunction<TFlexBasis>;
export declare const flexGrow: TUtilityFunction<TFlexGrow>;
export declare const flexShrink: TUtilityFunction<TFlexShrink>;
export declare const order: TUtilityFunction<TOrder>;
export declare const gridAutoFlow: TUtilityFunction<TGridAutoFlow>;
export declare const gridTemplateColumns: TUtilityFunction<TGridTemplateColumns>;
export declare const gridAutoColumns: TUtilityFunction<TGridAutoColumns>;
export declare const gridColumn: TUtilityFunction<TGridColumn>;
export declare const gridColumnStart: TUtilityFunction<TGridColumnStart>;
export declare const gridColumnEnd: TUtilityFunction<TGridColumnEnd>;
export declare const gridTemplateRows: TUtilityFunction<TGridTemplateRows>;
export declare const gridAutoRows: TUtilityFunction<TGridAutoRows>;
export declare const gridRow: TUtilityFunction<TGridRow>;
export declare const gridRowStart: TUtilityFunction<TGridRowStart>;
export declare const gridRowEnd: TUtilityFunction<TGridRowEnd>;
export declare const gap: TUtilityFunction<TGap>;
export declare const padding: TUtilityFunction<TPadding>;
export declare const margin: TUtilityFunction<TMargin>;
export declare const space: TUtilityFunction<TSpace>;
export declare const appearance: TUtilityFunction<TAppearance>;
export declare const pointerEvents: TUtilityFunction<TPointerEvents>;
export declare const resize: TUtilityFunction<TResize>;
export declare const userSelect: TUtilityFunction<TUserSelect>;
export declare const scrollSnap: TUtilityFunction<TScrollSnap>;
export declare const scrollBehavior: TUtilityFunction<TScrollBehavior>;
export declare const touchAction: TUtilityFunction<TTouchAction>;
export declare const cursor: TUtilityFunction<TCursor>;
export declare const caretColor: TUtilityFunction<TCaretColor>;
export declare const willChange: TUtilityFunction<TWillChange>;
export declare const accentColor: TUtilityFunction<TAccentColor>;
export declare const scrollPadding: TUtilityFunction<TScrollPadding>;
export declare const scrollMargin: TUtilityFunction<TScrollMargin>;
export declare const display: TUtilityFunction<TDisplay>;
export declare const boxDecorationBreak: TUtilityFunction<TBoxDecorationBreak>;
export declare const boxSizing: TUtilityFunction<TBoxSizing>;
export declare const container: TUtilityFunction<TContainer>;
export declare const float: TUtilityFunction<TFloat>;
export declare const clear: TUtilityFunction<TClear>;
export declare const isolation: TUtilityFunction<TIsolation>;
export declare const objectFit: TUtilityFunction<TObjectFit>;
export declare const overflow: TUtilityFunction<TOverflow>;
export declare const overscrollBehavior: TUtilityFunction<TOverscrollBehavior>;
export declare const position: TUtilityFunction<TPosition>;
export declare const visibility: TUtilityFunction<TVisibility>;
export declare const breakBefore: TUtilityFunction<TBreakBefore>;
export declare const breakInside: TUtilityFunction<TBreakInside>;
export declare const breakAfter: TUtilityFunction<TBreakAfter>;
export declare const objectPosition: TUtilityFunction<TObjectPosition>;
export declare const inset: TUtilityFunction<TInset>;
export declare const zIndex: TUtilityFunction<TZIndex>;
export declare const aspectRatio: TUtilityFunction<TAspectRatio>;
export declare const columns: TUtilityFunction<TColumns>;
export declare const width: TUtilityFunction<TWidth>;
export declare const minWidth: TUtilityFunction<TMinWidth>;
export declare const maxWidth: TUtilityFunction<TMaxWidth>;
export declare const height: TUtilityFunction<THeight>;
export declare const minHeight: TUtilityFunction<TMinHeight>;
export declare const maxHeight: TUtilityFunction<TMaxHeight>;
export declare const fill: TUtilityFunction<TFill>;
export declare const stroke: TUtilityFunction<TStroke>;
export declare const strokeWidth: TUtilityFunction<TStrokeWidth>;
export declare const hardwareAcceleration: TUtilityFunction<THardwareAcceleration>;
export declare const scale: TUtilityFunction<TScale>;
export declare const rotate: TUtilityFunction<TRotate>;
export declare const translate: TUtilityFunction<TTranslate>;
export declare const skew: TUtilityFunction<TSkew>;
export declare const transformOrigin: TUtilityFunction<TTransformOrigin>;
export declare const fontSmoothing: TUtilityFunction<TFontSmoothing>;
export declare const fontStyle: TUtilityFunction<TFontStyle>;
export declare const fontVariantNumeric: TUtilityFunction<TFontVariantNumeric>;
export declare const listStylePosition: TUtilityFunction<TListStylePosition>;
export declare const textAlign: TUtilityFunction<TTextAlign>;
export declare const textDecoration: TUtilityFunction<TTextDecoration>;
export declare const textTransform: TUtilityFunction<TTextTransform>;
export declare const textOverflow: TUtilityFunction<TTextOverflow>;
export declare const verticalAlign: TUtilityFunction<TVerticalAlign>;
export declare const whitespace: TUtilityFunction<TWhitespace>;
export declare const wordBreak: TUtilityFunction<TWordBreak>;
export declare const textDecorationStyle: TUtilityFunction<TTextDecorationStyle>;
export declare const fontFamily: TUtilityFunction<TFontFamily>;
export declare const fontSize: TUtilityFunction<TFontSize>;
export declare const fontWeight: TUtilityFunction<TFontWeight>;
export declare const letterSpacing: TUtilityFunction<TLetterSpacing>;
export declare const lineHeight: TUtilityFunction<TLineHeight>;
export declare const listStyleType: TUtilityFunction<TListStyleType>;
export declare const placeholderColor: TUtilityFunction<TPlaceholderColor>;
export declare const placeholderOpacity: TUtilityFunction<TPlaceholderOpacity>;
export declare const textColor: TUtilityFunction<TTextColor>;
export declare const textOpacity: TUtilityFunction<TTextOpacity>;
export declare const content: TUtilityFunction<TContent>;
export declare const textIndent: TUtilityFunction<TTextIndent>;
export declare const textDecorationColor: TUtilityFunction<TTextDecorationColor>;
export declare const textDecorationThickness: TUtilityFunction<TTextDecorationThickness>;
export declare const textUnderlineOffset: TUtilityFunction<TTextUnderlineOffset>;
export declare const TW: {
    screenReaders: TUtilityFunction<TScreenReaders>;
    backgroundAttachment: TUtilityFunction<TBackgroundAttachment>;
    backgroundClip: TUtilityFunction<TBackgroundClip>;
    backgroundOrigin: TUtilityFunction<TBackgroundOrigin>;
    backgroundRepeat: TUtilityFunction<TBackgroundRepeat>;
    backgroundOpacity: TUtilityFunction<TBackgroundOpacity>;
    backgroundColor: TUtilityFunction<TBackgroundColor>;
    backgroundPosition: TUtilityFunction<TBackgroundPosition>;
    backgroundSize: TUtilityFunction<TBackgroundSize>;
    backgroundImage: TUtilityFunction<"bg-none">;
    gradientColorStops: TUtilityFunction<TGradientColorStops>;
    borderStyle: TUtilityFunction<TBorderStyle>;
    divideStyle: TUtilityFunction<TDivideStyle>;
    outlineStyle: TUtilityFunction<TOutlineStyle>;
    borderColor: TUtilityFunction<TBorderColor>;
    borderOpacity: TUtilityFunction<TBorderOpacity>;
    borderRadius: TUtilityFunction<TBorderRadius>;
    borderWidth: TUtilityFunction<TBorderWidth>;
    divideColor: TUtilityFunction<TDivideColor>;
    divideOpacity: TUtilityFunction<TDivideOpacity>;
    divideWidth: TUtilityFunction<TDivideWidth>;
    ringColor: TUtilityFunction<TRingColor>;
    ringWidth: TUtilityFunction<TRingWidth>;
    ringOpacity: TUtilityFunction<TRingOpacity>;
    ringOffsetColor: TUtilityFunction<TRingOffsetColor>;
    ringOffsetWidth: TUtilityFunction<TRingOffsetWidth>;
    outlineOffset: TUtilityFunction<TOutlineOffset>;
    outlineWidth: TUtilityFunction<TOutlineWidth>;
    outlineColor: TUtilityFunction<TOutlineColor>;
    borderCollapse: TUtilityFunction<TBorderCollapse>;
    tableLayout: TUtilityFunction<TTableLayout>;
    mixBlendMode: TUtilityFunction<TMixBlendMode>;
    backgroundBlendMode: TUtilityFunction<TBackgroundBlendMode>;
    boxShadow: TUtilityFunction<TBoxShadow>;
    boxShadowColor: TUtilityFunction<TBoxShadowColor>;
    opacity: TUtilityFunction<TOpacity>;
    transitionProperty: TUtilityFunction<TTransitionProperty>;
    transitionDuration: TUtilityFunction<TTransitionDuration>;
    transitionTimingFunction: TUtilityFunction<TTransitionTimingFunction>;
    transitionDelay: TUtilityFunction<TTransitionDelay>;
    animation: TUtilityFunction<TAnimation>;
    filter: TUtilityFunction<TFilter>;
    backdropFilter: TUtilityFunction<TBackdropFilter>;
    blur: TUtilityFunction<TBlur>;
    brightness: TUtilityFunction<TBrightness>;
    contrast: TUtilityFunction<TContrast>;
    dropShadow: TUtilityFunction<"drop-shadow">;
    grayscale: TUtilityFunction<TGrayscale>;
    hueRotate: TUtilityFunction<THueRotate>;
    invert: TUtilityFunction<TInvert>;
    saturate: TUtilityFunction<TSaturate>;
    sepia: TUtilityFunction<TSepia>;
    backdropBlur: TUtilityFunction<TBackdropBlur>;
    backdropBrightness: TUtilityFunction<TBackdropBrightness>;
    backdropContrast: TUtilityFunction<TBackdropContrast>;
    backdropGrayscale: TUtilityFunction<TBackdropGrayscale>;
    backdropHueRotate: TUtilityFunction<TBackdropHueRotate>;
    backdropInvert: TUtilityFunction<TBackdropInvert>;
    backdropOpacity: TUtilityFunction<TBackdropOpacity>;
    backdropSaturate: TUtilityFunction<TBackdropSaturate>;
    backdropSepia: TUtilityFunction<TBackdropSepia>;
    flexDirection: TUtilityFunction<TFlexDirection>;
    flexWrap: TUtilityFunction<TFlexWrap>;
    alignItems: TUtilityFunction<TAlignItems>;
    alignContent: TUtilityFunction<TAlignContent>;
    alignSelf: TUtilityFunction<TAlignSelf>;
    placeContent: TUtilityFunction<TPlaceContent>;
    placeItems: TUtilityFunction<TPlaceItems>;
    placeSelf: TUtilityFunction<TPlaceSelf>;
    justifyContent: TUtilityFunction<TJustifyContent>;
    justifyItems: TUtilityFunction<TJustifyItems>;
    justifySelf: TUtilityFunction<TJustifySelf>;
    flex: TUtilityFunction<TFlex>;
    flexBasis: TUtilityFunction<TFlexBasis>;
    flexGrow: TUtilityFunction<TFlexGrow>;
    flexShrink: TUtilityFunction<TFlexShrink>;
    order: TUtilityFunction<TOrder>;
    gridAutoFlow: TUtilityFunction<TGridAutoFlow>;
    gridTemplateColumns: TUtilityFunction<"grid-cols-none">;
    gridAutoColumns: TUtilityFunction<TGridAutoColumns>;
    gridColumn: TUtilityFunction<TGridColumn>;
    gridColumnStart: TUtilityFunction<TGridColumnStart>;
    gridColumnEnd: TUtilityFunction<TGridColumnEnd>;
    gridTemplateRows: TUtilityFunction<"grid-rows-none">;
    gridAutoRows: TUtilityFunction<TGridAutoRows>;
    gridRow: TUtilityFunction<TGridRow>;
    gridRowStart: TUtilityFunction<TGridRowStart>;
    gridRowEnd: TUtilityFunction<TGridRowEnd>;
    gap: TUtilityFunction<TGap>;
    padding: TUtilityFunction<TPadding>;
    margin: TUtilityFunction<TMargin>;
    space: TUtilityFunction<TSpace>;
    appearance: TUtilityFunction<"appearance-none">;
    pointerEvents: TUtilityFunction<TPointerEvents>;
    resize: TUtilityFunction<TResize>;
    userSelect: TUtilityFunction<TUserSelect>;
    scrollSnap: TUtilityFunction<TScrollSnap>;
    scrollBehavior: TUtilityFunction<TScrollBehavior>;
    touchAction: TUtilityFunction<TTouchAction>;
    cursor: TUtilityFunction<TCursor>;
    caretColor: TUtilityFunction<TCaretColor>;
    willChange: TUtilityFunction<TWillChange>;
    accentColor: TUtilityFunction<TAccentColor>;
    scrollPadding: TUtilityFunction<TScrollPadding>;
    scrollMargin: TUtilityFunction<TScrollMargin>;
    display: TUtilityFunction<TDisplay>;
    boxDecorationBreak: TUtilityFunction<TBoxDecorationBreak>;
    boxSizing: TUtilityFunction<TBoxSizing>;
    container: TUtilityFunction<"container">;
    float: TUtilityFunction<TFloat>;
    clear: TUtilityFunction<TClear>;
    isolation: TUtilityFunction<TIsolation>;
    objectFit: TUtilityFunction<TObjectFit>;
    overflow: TUtilityFunction<TOverflow>;
    overscrollBehavior: TUtilityFunction<TOverscrollBehavior>;
    position: TUtilityFunction<TPosition>;
    visibility: TUtilityFunction<TVisibility>;
    breakBefore: TUtilityFunction<TBreakBefore>;
    breakInside: TUtilityFunction<TBreakInside>;
    breakAfter: TUtilityFunction<TBreakAfter>;
    objectPosition: TUtilityFunction<TObjectPosition>;
    inset: TUtilityFunction<TInset>;
    zIndex: TUtilityFunction<TZIndex>;
    aspectRatio: TUtilityFunction<TAspectRatio>;
    columns: TUtilityFunction<TColumns>;
    width: TUtilityFunction<TWidth>;
    minWidth: TUtilityFunction<TMinWidth>;
    maxWidth: TUtilityFunction<TMaxWidth>;
    height: TUtilityFunction<THeight>;
    minHeight: TUtilityFunction<TMinHeight>;
    maxHeight: TUtilityFunction<TMaxHeight>;
    fill: TUtilityFunction<TFill>;
    stroke: TUtilityFunction<TStroke>;
    strokeWidth: TUtilityFunction<TStrokeWidth>;
    hardwareAcceleration: TUtilityFunction<"transform-gpu">;
    scale: TUtilityFunction<TScale>;
    rotate: TUtilityFunction<TRotate>;
    translate: TUtilityFunction<TTranslate>;
    skew: TUtilityFunction<TSkew>;
    transformOrigin: TUtilityFunction<TTransformOrigin>;
    fontSmoothing: TUtilityFunction<TFontSmoothing>;
    fontStyle: TUtilityFunction<TFontStyle>;
    fontVariantNumeric: TUtilityFunction<TFontVariantNumeric>;
    listStylePosition: TUtilityFunction<TListStylePosition>;
    textAlign: TUtilityFunction<TTextAlign>;
    textDecoration: TUtilityFunction<TTextDecoration>;
    textTransform: TUtilityFunction<TTextTransform>;
    textOverflow: TUtilityFunction<TTextOverflow>;
    verticalAlign: TUtilityFunction<TVerticalAlign>;
    whitespace: TUtilityFunction<TWhitespace>;
    wordBreak: TUtilityFunction<TWordBreak>;
    textDecorationStyle: TUtilityFunction<TTextDecorationStyle>;
    fontFamily: TUtilityFunction<TFontFamily>;
    fontSize: TUtilityFunction<TFontSize>;
    fontWeight: TUtilityFunction<TFontWeight>;
    letterSpacing: TUtilityFunction<TLetterSpacing>;
    lineHeight: TUtilityFunction<TLineHeight>;
    listStyleType: TUtilityFunction<TListStyleType>;
    placeholderColor: TUtilityFunction<TPlaceholderColor>;
    placeholderOpacity: TUtilityFunction<TPlaceholderOpacity>;
    textColor: TUtilityFunction<TTextColor>;
    textOpacity: TUtilityFunction<TTextOpacity>;
    content: TUtilityFunction<"content-none">;
    textIndent: TUtilityFunction<TTextIndent>;
    textDecorationColor: TUtilityFunction<TTextDecorationColor>;
    textDecorationThickness: TUtilityFunction<TTextDecorationThickness>;
    textUnderlineOffset: TUtilityFunction<TTextUnderlineOffset>;
};
export declare type TTailwindString = "TAILWIND_STRING";
export declare type TArg = null | undefined | TTailwindString;
export declare type TTailwind = (...args: TArg[]) => TTailwindString;
export declare const classnames: TTailwind;
export default classnames;
